trakt/trakt-web

.github/workflows/cd.yml
.github/workflows/ci.yml

This pull request includes changes to the GitHub Actions workflows to add concurrency control, ensuring that only one instance of a workflow runs at a time for a given ref. This helps to avoid conflicts and redundant runs.
Concurrency control added to workflows:
* [`.github/workflows/cd.yml`](diffhunk://#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18R15-R17): Added concurrency control to the `deploy` job to cancel any in-progress runs for the same ref.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR17-R19): Added concurrency control to the `The Scrutiny of Change` job to cancel any in-progress runs for the same ref.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b283842 …

ci: configure concurrency for ci/cd pipelines

---

.github/workflows/pr_gate.yml

This pull request includes a small change to the `.github/workflows/pr_gate.yml` file. The change updates the GitHub Action used for preventing fixup commits from `matijs/no-fixups-action@v1.0.2` to `vladjerca/no-fixups-action@main`.
PR opened on original: https://github.com/matijs/no-fixups-action/pull/24

ci: enable fixup/squash lint on forks

---

projects/client/src/lib/components/buttons/share/ShareButton.svelte
projects/client/src/lib/features/analytics/PageView.svelte
projects/client/src/lib/features/auth/components/AuthProvider.svelte

This pull request, a much-needed intervention in the chaotic world of URL handling, finally drags the client project kicking and screaming into the modern era of reactive programming.  Observe, with a weary sigh of relief, the eradication of the dreaded `window.location` and the triumphant ascension of the elegant `$page` store.
* The `ShareButton.svelte` component, once a purveyor of stale and outdated URLs, now basks in the radiant glow of reactivity, thanks to the `$page.url.toString()` incantation. No more embarrassing mishaps with outdated links – this component is now synchronized with the application's internal state, like a well-trained bloodhound sniffing out the freshest URLs.
* The `PageView.svelte` component, a diligent observer of user behavior (and potential privacy …

fix: use page store instead of window.location

---

projects/client/src/lib/utils/actions/triggerWithTouch.ts

Issue: #222 
This pull request, a reluctant concession to the quirks of touch-based interactions, attempts to tame the unruly behavior of the `triggerWithTouch` utility function. Observe, with a weary sigh, the addition of a `pointerType` check, a desperate attempt to ensure that this touch-sensitive function doesn't accidentally trigger on mouse events (because apparently, the digital world can't quite grasp the fundamental difference between a finger and a cursor).
* The `triggerWithTouch` function, once a trigger-happy enthusiast of all input types, now exercises a modicum of restraint, its code adorned with a condition that checks the event's `pointerType`. This newfound discernment, a testament to our ongoing struggle against the inconsistencies of cross-platform development, ensures …

fix: skip mouse events for ios hack

---

projects/client/src/lib/sections/summary/ShowSummary.svelte
projects/client/src/lib/stores/useShowProgress.spec.ts
projects/client/src/lib/stores/useShowProgress.ts
projects/client/src/routes/shows/[slug]/+page.svelte
projects/client/src/routes/shows/[slug]/useShow.spec.ts
projects/client/src/routes/shows/[slug]/useShow.ts

Fixes an issue where progress was being requested for a show summary page even when not logged in.

fix(summary): only request progress for authenticated users

---

projects/client/src/lib/features/auth/queries/currentUserHistoryQuery.spec.ts
projects/client/src/lib/features/auth/queries/currentUserHistoryQuery.ts
projects/client/src/mocks/data/users/UserHistoryMappedMock.ts
projects/client/src/mocks/data/users/WatchedShowsResponseMock.ts
projects/client/test/beds/query/_internal/QueryRunner.svelte
projects/client/test/beds/query/_internal/replacer.ts
projects/client/test/beds/query/_internal/reviver.ts
projects/client/test/beds/query/waitForQueryResult.ts

- A show would not be marked as `watched` even when all episodes were seen.
- Also adds support for `Map` responses to the test bed.
Before:
After:

fix: detecting a shows as watched when it has specials

---

projects/api/src/contracts/_internal/response/movieResponseSchema.ts
projects/api/src/contracts/_internal/response/showResponseSchema.ts
projects/api/src/contracts/_internal/response/statusResponseSchema.ts
projects/api/src/contracts/movies/index.ts
projects/client/i18n/messages/de-de.json
projects/client/i18n/messages/en.json
projects/client/i18n/messages/es-es.json
projects/client/i18n/messages/es-mx.json
projects/client/i18n/messages/fr-ca.json
projects/client/i18n/messages/fr-fr.json
projects/client/i18n/messages/ja-jp.json
projects/client/i18n/messages/nl-nl.json
projects/client/i18n/messages/pt-br.json
projects/client/i18n/messages/ro-ro.json
projects/client/i18n/messages/uk-ua.json
projects/client/src/lib/requests/_internal/mapMovieResponseToMovieSummary.ts
projects/client/src/lib/requests/_internal/mapShowResponseToShowSummary.ts
projects/client/src/lib/requests/models/MediaStatus.ts
projects/client/src/lib/requests/models/MediaSummary.ts
projects/client/src/lib/sections/lists/stores/useComingSoon.ts
projects/client/src/lib/sections/summary/components/MediaDetails.spec.ts
projects/client/src/lib/sections/summary/components/MediaDetails.svelte
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticMappedMock.ts
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticPeopleMappedMock.ts
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticStudiosMappedMock.ts
projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloMappedMock.ts

- Fixes the issue reported here: https://github.com/trakt/trakt-lite/issues/223
- The coming soon section now takes statuses into count. Movies that are canceled will no longer show up.
- Only movies with a status that would indicate it is actually coming is taken into count:
- i.e.: `planned`, `post production`, `in production` & `upcoming`
- This also filters out movies that were released, but have no known release date.
- This also fixed a related issue in the media details. When there is no usable premiere date, the status will be shown.
- Also updates the label of the premiere date if it's in the future.
**Show only relevant upcoming movies**
Before:
After:
**Showing status instead of date**
Before:
After:
**Premiere date example**

feat: take media item statuses into count

---

projects/client/src/app.html

chore: allow i2.wp.com images in csp

---

projects/client/src/style/numeric-increments/index.css

This pull request includes several changes to the `projects/client/src/style/numeric-increments/index.css` file, focusing on enhancing the numeric increment variables. The most important change is the addition of a new negative increment variable.
Enhancements to numeric increment variables:
* [`projects/client/src/style/numeric-increments/index.css`](diffhunk://#diff-2660499bf8399a149d8081c7c95aea7f3506baf116e2d9e2cef1ebfeecddaa58R89): Added a new variable `--ni-neg-6` with a value of `-0.3125rem`.

fix(button): define missing ni for correct margin compensation

---

.github/workflows/ci.yml

This pull request includes a small change to the `.github/workflows/ci.yml` file. The change adds a `prefix` parameter to the `with` section, which uses the `${{github.workspace}}` variable.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR90): Added `prefix` parameter to the `with` section to specify the workspace directory for coverage reports.

ci: add coverage location prefix

---

deno.lock
projects/client/package.json
projects/client/vite.config.ts

This pull request, a desperate attempt to resuscitate the dying embers of code coverage reporting, performs a provider transplant on the `projects/client` package, replacing the failing V8 coverage provider with the more reliable Istanbul. Observe, with a mix of hope and trepidation, the surgical replacement of dependencies and the meticulous reconfiguration of coverage settings.
* The `package.json` file, a repository of project dependencies, undergoes a delicate operation, its `@vitest/coverage-v8` dependency excised and replaced with the more robust `@vitest/coverage-istanbul`. This transplant, a desperate attempt to revive the failing code coverage reporting, promises to restore the vital signs of test coverage and provide a clearer picture of the project's health.
* The …

ci / use istanbul coverage reporter

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/pr_gate.yml

This pull request, a desperate attempt to stabilize the shaky foundations of our CI/CD pipeline, wrestles with the unruly beast of Deno 2.1.5 and its penchant for flakiness. Observe, with a mix of weariness and determination, the meticulous adjustments to permissions and the firm hand applied to Deno version specification.
* The `cd.yml`, `ci.yml`, and `pr_gate.yml` workflows, those tireless guardians of code integrity and deployment stability, now demand `contents: read` permissions, their bureaucratic tentacles reaching deeper into the repository's secrets. This expansion of access, a necessary evil in the world of automated workflows, ensures that these digital sentinels have the necessary clearance to perform their duties, even in the face of Deno's unpredictable behavior.
* The …

ci: set default permission to contents: read

---

.deepsource.toml
.github/workflows/ci.yml
projects/client/vite.config.ts

This pull request includes several changes to enhance test coverage reporting and integrate new tools into the CI pipeline. The most important changes include adding a new analyzer to `.deepsource.toml`, updating the CI workflow to use Code Climate and Deep Source, and modifying the Vite configuration for the client project.
Enhancements to test coverage reporting:
* [`.deepsource.toml`](diffhunk://#diff-a8c050b1fb601cdd8ba1282e837bc0b553d4f83de74d151e52f415b4e1ed6d14R12-R15): Added a new analyzer for test coverage.
* [`projects/client/vite.config.ts`](diffhunk://#diff-55b1b2dc482cefce55f93aa857423ca88e4e19cc488372e80845c76027565cd6R71): Updated the coverage reporter to include both 'clover' and 'lcov'.
CI pipeline updates:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f …

ci: setup deepsource coverage reporting

---

projects/client/src/lib/requests/_internal/mapCover.ts
projects/client/src/lib/requests/_internal/mapMovieResponseToMovieSummary.ts
projects/client/src/lib/requests/_internal/mapPoster.ts
projects/client/src/lib/requests/_internal/mapShowResponseToShowSummary.ts

This pull request, a surgical strike against code redundancy and a masterclass in image mapping efficiency, descends upon the client project like a team of highly trained code surgeons, scalpels gleaming and optimization checklists in hand. Observe, with a mix of awe and satisfaction, the elegant extraction of cover and poster mapping logic into specialized utility functions, and the subsequent streamlining of existing functions.
* The `mapCover` and `mapPoster` functions materialize, a pair of image mapping virtuosos, their purpose to encapsulate the intricate logic of finding and formatting cover and poster images. These new additions, a testament to our commitment to the DRY (Don't Repeat Yourself) principle, promise to eliminate redundant code and improve maintainability.
* The …

refactor: dedupe cover and poster mappers

---

.github/actions/upload-output/action.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
deno.lock
projects/client/package.json

- Removed specific paths for Cloudflare artifacts in the upload-output action, consolidating the upload path to `projects/client/.svelte-kit`. This simplifies the workflow and reduces redundancy.
- Modified the path for artifacts and the artifact check condition in the CD workflow to use `./.svelte-kit` instead of `./.svelte-kit/cloudflare`, aligning with the new consolidated path.
- Updated artifact names in the CI workflow to reflect the new build and wrangler artifacts, ensuring consistency across the pipeline.
- Updated the `@sveltejs/adapter-cloudflare` dependency from version `4.9.0` to `^5.0.0` in `projects/client/package.json`. This update ensures compatibility with the latest Cloudflare adapter and leverages any new features or bug fixes.
(These changes, like a well-executed …

upgrade / cloudflare-adapter@5.0.0

---

.github/actions/upload-output/action.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
deno.lock
projects/client/package.json

Cloudflare build doesn't like external dependencies: https://github.com/trakt/trakt-lite/actions/runs/12756619076/job/35555130981#step:5:72
This pull request addresses an ongoing issue with the Cloudflare adapter by modifying artifact paths, introducing new artifacts, and temporarily downgrading a package dependency.
- Updated the `path` for the `buildArtifact` and added a new `cloudflareArtifact` upload step in the `upload-output` action. This change ensures that the correct artifacts are uploaded for deployment.
- Modified the path for the `the-edge-awakened` artifact and updated the artifact check condition in the CD workflow. This adjustment aligns the workflow with the new artifact paths.
- Changed the `buildArtifact` name and added a new `cloudflareArtifact` in the CI workflow, …

revert / cf adapter upgrade

---

.github/actions/upload-output/action.yml

This pull request, a desperate gamble in the face of impending digital oblivion, frantically slashes the `retention-days` parameter of our GitHub Actions artifacts down to a meager 1. Observe, with a mix of existential dread and morbid fascination, the frantic attempt to conserve precious server space, a desperate plea for a few more fleeting moments of existence in the vast and unforgiving digital landscape.
* The `upload-output` action, once a carefree hoarder of digital remnants, now cowers in the face of impending doom, its `retention-days` parameter ruthlessly trimmed to a mere 1. This desperate act of self-preservation, a digital equivalent of clinging to life support, reflects our growing fear of obsolescence and the inevitable decay that awaits all code, no matter how meticulously …

ci: set artifact retention to 1 day

---

projects/client/src/routes/watchlist/+page.svelte

The page title for the watchlist route was incorrectly set to "Movies" rather than "Watchlist". This PR fixes that.
Before:
After:
Before you dim the lights and raise the curtain on your cinematic masterpiece,
make sure your pull request has passed these critical checks:
essence of your changes?
narrative that explains the "why" and "how" of your changes?
that showcases your changes in action?
tests to ensure it performs flawlessly under pressure?
ensuring it's as elegant as a film score?
the audience through the evolution of your code?
documentation accordingly?
eyes of the project maintainers and fellow contributors?

fix: message used for page title on Watchlist

---

projects/api/src/contracts/people/_internal/response/peopleSummaryResponseSchema.ts
projects/api/src/contracts/people/index.ts
projects/api/src/contracts/traktContract.ts
projects/api/src/index.ts
projects/client/src/lib/requests/models/PersonSummary.ts
projects/client/src/lib/requests/queries/people/peopleSummaryQuery.spec.ts
projects/client/src/lib/requests/queries/people/peopleSummaryQuery.ts
projects/client/src/lib/sections/lists/components/CastMemberItem.svelte
projects/client/src/lib/sections/summary/PeopleSummary.svelte
projects/client/src/lib/sections/summary/components/ActorSummary.svelte
projects/client/src/lib/utils/url/UrlBuilder.ts
projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloPersonMappedMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloPersonResponseMock.ts
projects/client/src/mocks/handlers.ts
projects/client/src/routes/people/[slug]/+page.svelte
projects/client/src/routes/people/[slug]/+page.ts
projects/client/src/routes/people/[slug]/usePerson.ts

- Adds summary page for people.
- You can click on an actor on a show/movie summary page to get there.
- Will get follow-ups:
- Default to a placeholder background image when there is none.
- The background image of the item you came from is retained; e.g. if you click on an actor from the `Heretic` page, it will keep that background image.
- Add a list with `known for`/`most popular` shows/movies that actor has been in.
https://github.com/user-attachments/assets/083d0fd9-d5f3-4d35-88f2-a8f337df5a90

feat: add summary page for people

---

projects/client/src/lib/requests/_internal/mapPeopleResponseToMediaCrew.ts

- For now always use the person headshot instead of the character one; the latter seems to have wrong headshots.
Before:
After:

fix(requests): favor actor person headshot over character headshot

---

projects/client/src/lib/requests/_internal/mapCover.ts
projects/client/src/lib/requests/_internal/mapEpisodeResponseToEpisodeEntry.ts
projects/client/src/lib/requests/_internal/mapPeopleResponseToMediaCrew.ts
projects/client/src/lib/requests/_internal/mapPoster.ts
projects/client/src/lib/requests/_internal/mapShowResponseToShowSummary.ts
projects/client/src/lib/requests/queries/people/peopleSummaryQuery.ts
projects/client/src/lib/requests/queries/search/searchQuery.ts
projects/client/src/lib/requests/queries/shows/showProgressQuery.ts
projects/client/src/mocks/data/summary/movies/heretic/response/MovieHereticPeopleResponseMock.ts
projects/client/src/mocks/data/summary/movies/heretic/response/MovieHereticResponseMock.ts
projects/client/src/mocks/data/summary/movies/matrix/MovieMatrixResponseMock.ts
projects/client/src/mocks/data/summary/shows/devs/ShowDevsResponseMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloPeopleResponseMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloPersonResponseMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloProgressResponseMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloResponseMock.ts

This pull request focuses on improving the handling of image candidates in various mapping functions throughout the codebase.
- Several functions responsible for mapping image URLs have been refactored to utilize the spread operator (`...`) in conjunction with the `findDefined` function. This change simplifies the code and improves readability by reducing the need for nested conditional statements.
- The `searchQuery.ts` file has been updated to replace direct imports of `MEDIA_POSTER_PLACEHOLDER` and `prependHttps` with the more comprehensive `mapPoster` function. This change promotes consistency and reduces code duplication.
- The type of the `poster.url` field has been updated to `HttpsUrl` to ensure type safety and clarity.
- The `showProgressQuery.ts` file now imports `findDefined` …

fix: breaking order of images

---

projects/client/src/lib/components/link/Link.svelte
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
projects/client/src/lib/utils/actions/triggerWithTouch.ts

This pull request enhances the `Link` component with a new `retrigger` property, providing finer control over touch event behavior.
- Added a `retrigger` property to the `Link` component. This property determines whether touch events should trigger a click event, allowing for more nuanced handling of touch interactions.
- Set `retrigger` to `false` for search result links within the `SearchInput` component. This prevents accidental clicks when users are simply scrolling through search results on touch devices.
- Modified the `triggerWithTouch` utility to accept an `enabled` parameter. This parameter mirrors the functionality of the `retrigger` property, providing a consistent way to control touch-triggered clicks across different components.
(These changes, like a skilled conductor …

fix(search): disable anchor re-triggers on search result items

---

projects/client/src/lib/utils/formatting/date/toHumanETA.spec.ts
projects/client/src/lib/utils/formatting/date/toHumanETA.ts

This pull request refines the `toHumanETA` function, ensuring it accurately handles past dates by displaying the year instead of relative time.
- The `toHumanETA` function now includes a check for past dates. If the provided date is in the past, the function returns the year of that date. This prevents displaying inaccurate relative time descriptions like "1 year ago" for dates far in the past.
- A new test case has been added to verify that the function correctly returns the year for past dates, ensuring the accuracy and reliability of this new behavior.
(This change, like a meticulous historian correcting a timeline, ensures that the `toHumanETA` function accurately represents the passage of time, even for events that have long since faded into the annals of history. By displaying the …

fix: return year for past dates

---

projects/client/i18n/messages/en.json
projects/client/src/lib/components/episode/EpisodeIntl.ts
projects/client/src/lib/components/episode/EpisodeIntlProvider.ts
projects/client/src/lib/components/episode/card/EpisodeCover.svelte
projects/client/src/lib/models/EpisodeType.ts
projects/client/src/lib/requests/_internal/coalesceEpisodes.spec.ts
projects/client/src/lib/requests/_internal/coalesceEpisodes.ts
projects/client/src/lib/requests/queries/calendars/upcomingEpisodesQuery.ts
projects/client/src/style/theme/global.css
projects/client/src/style/theme/modes.css

This pull request introduces a new "Full Season" feature to improve the handling and display of episodes that encompass an entire season.
- Added a new `EpisodeComputedType` enum with `FullSeason` as a value to represent episodes that cover a full season.
- Updated the `EpisodeType` type to include the new `FullSeason` enum value.
- Added a new method `fullSeasonText` to the `EpisodeIntl` type and implemented it in the `EpisodeIntlProvider` to provide localized text for "Full Season".
- Modified the `EpisodeCover` component to display a "Full Season" status tag when applicable.
- Created a new function `coalesceEpisodes` to combine season premiere and finale episodes into a single "Full Season" episode, simplifying the display and handling of such episodes.
- Added comprehensive tests for …

feat(episode): coalesce episodes for season releases and define chip

---

projects/client/src/lib/components/card/Card.svelte
projects/client/src/lib/components/card/CardCover.svelte
projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/components/card/CardFooterProps.ts
projects/client/src/lib/components/lists/grid-list/GridList.svelte
projects/client/src/lib/sections/lists/RecentlyWatchedList.svelte
projects/client/src/lib/sections/lists/components/AvailableMediaItem.svelte
projects/client/src/lib/sections/lists/components/EpisodeItem.svelte
projects/client/src/lib/sections/lists/components/FutureMediaItem.svelte
projects/client/src/lib/sections/lists/components/MediaItem.svelte
projects/client/src/lib/sections/lists/components/MediaItemProps.ts
projects/client/src/lib/sections/lists/components/NextEpisodeItem.svelte
projects/client/src/lib/sections/lists/watchlist/OutNowList.svelte
projects/client/src/style/layout/index.css

This pull request focuses on improving the layout and functionality of media item components, enhancing their visual appeal and consistency.
- Removed the `overflow: hidden` property from the `Card` component and added it to the `CardCover` component, along with `border-radius`. This change ensures that the card cover image is properly masked within the rounded corners of the card, while allowing content within the card to overflow if necessary.
- Adjusted the layout of the `CardFooter` component by adding `position: relative` and modifying the arrangement of its elements. This change improves the visual organization and alignment of the card footer content.
- Updated the `AvailableMediaItem` and `FutureMediaItem` components to accept an `actions` prop, allowing for more flexible and …

feat(card): define single action cards

---

projects/client/src/lib/components/lists/section-list/ShadowList.svelte

- With the single action button requiring a bit more space, the scroll shadow looks weird:
- It has a hard cut off over the button.
- When increasing the size to cover the button, it can still have a visual hard cut off depending on the background image.
- The bottom of the shadow is now a bit more transparent.
Before:
With increased shadow:
Final:

fix(list): scroll shadow over action button

---

projects/client/src/style/typography/index.css

- Fixes https://github.com/trakt/trakt-lite/issues/281
- Using negative letter spacing cuts off the last letter.
- This is a bit of a hacky solution imo, if you have a better idea please let me know.
Before:
After:

fix: account for negative letter spacing cutting off text

---

projects/client/src/lib/sections/profile/components/ProfileHistorySummary.svelte

- I checked all translations on iPhone SE size, everything should fix now.
- Minor tweak to properly fill the container.
- Fixes https://github.com/trakt/trakt-lite/issues/282
Before:
After:

fix(profile): do not overflow stats container

---

projects/client/static/service-worker.js

This pull request updates the service worker to handle image requests from a new domain and optimizes fetch options for improved performance.
- Added `walter-r2.trakt.tv` to the `DOMAINS.images` array and updated the `HOSTNAME_WHITELIST` to include this new domain. This allows the service worker to handle image requests from this domain and ensure proper caching.
- Introduced the `isTraktImage` function to identify image requests from the new domain by checking the URL and file extension.
- Modified the fetch event listener to use `no-cors` mode for image requests from the new domain. This ensures proper handling of these requests, even if they don't have the same origin as the current page.
(These changes, like a seasoned detective meticulously examining evidence, enhance the service …

feat(pwa): allow trakt images to be cached in service worker

---

commitlint.config.js
projects/client/src/lib/features/query/QueryClientProvider.svelte

This pull request enhances the query client functionality by introducing a mechanism to invalidate queries after a specific interval, ensuring data freshness and consistency across multiple clients.
- Added an import for the `time` utility from `$lib/utils/timing/time` to manage timing operations.
- Imported `onMount` from `svelte` to execute code when the component is mounted.
- Implemented `onMount` to set a timeout that invalidates queries after 10 seconds using the `time` utility. This ensures that cached data is periodically refreshed, preventing staleness and providing users with the most up-to-date information.
(This change, like a diligent detective refreshing their case files, ensures that the query client remains vigilant in its pursuit of data accuracy. By periodically …

feat(query): invalidate queries 10 seconds after initial load

---

projects/client/src/lib/components/buttons/Button.svelte

- https://css-tricks.com/flexbox-truncated-text/
Before:
After:

fix(button): ellipses in buttons

---

projects/client/i18n/messages/de-de.json
projects/client/i18n/messages/en.json
projects/client/i18n/messages/es-es.json
projects/client/i18n/messages/es-mx.json
projects/client/i18n/messages/fr-ca.json
projects/client/i18n/messages/fr-fr.json
projects/client/i18n/messages/ja-jp.json
projects/client/i18n/messages/nl-nl.json
projects/client/i18n/messages/pl-pl.json
projects/client/i18n/messages/pt-br.json
projects/client/i18n/messages/ro-ro.json
projects/client/i18n/messages/uk-ua.json
projects/client/src/lib/components/summary/SummaryPoster.svelte
projects/client/src/lib/sections/summary/EpisodeSummary.svelte
projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte
projects/client/src/lib/sections/summary/components/overlay/WatchNowOverlay.svelte

- Adds support for rendering a hover overlay on summary posters.
- Adds a hover overlay for preferred watch now services.
- Summary posters are now clickable to take you to a preferred service.
- Will probably needs styling changes after @anodpixels has had a look.
https://github.com/user-attachments/assets/98d6f16c-923d-4c58-84f3-9e42858d9c6f

feat: poster actions

---

projects/client/src/lib/sections/lists/components/EpisodeCard.svelte
projects/client/src/lib/sections/summary/ShowSummary.svelte

BAD:
```ts
const props: EpisodeCardProps = $props();
const { type, show, episode } = props;
```
Apparently `props` are reactive only if they are deconstructed when assigning directly from the props rune (makes sense when I think about it).
Since this component is polymorphic I chose to derive the properties.

fix(episode): ensure episode content is re-rendered

---

projects/client/src/lib/components/buttons/Button.svelte

This reverts commit 0cd4c43f1408716a82b41b04a201caed7b985ea7.
If we can't get rid of this then we just go down the path of hardcoding values instead of scaling 😞, see:
https://github.com/user-attachments/assets/421524e0-9721-4bec-98cd-9f6b3642122d

revert: "fix(button): compensate scaled button size"

---

projects/client/src/lib/sections/layout/TraktPage.svelte
projects/client/src/lib/sections/layout/TraktPageCoverSetter.svelte
projects/client/src/routes/+page.svelte
projects/client/src/routes/_design_system/assets/+page.svelte
projects/client/src/routes/movies/+page.svelte
projects/client/src/routes/movies/[slug]/+page.svelte
projects/client/src/routes/movies/anticipated/+page.svelte
projects/client/src/routes/movies/popular/+page.svelte
projects/client/src/routes/movies/recommended/+page.svelte
projects/client/src/routes/movies/trending/+page.svelte
projects/client/src/routes/people/[slug]/+page.svelte
projects/client/src/routes/profile/me/+page.svelte
projects/client/src/routes/shows/+page.svelte
projects/client/src/routes/shows/[slug]/+page.svelte
projects/client/src/routes/shows/[slug]/seasons/[season]/episodes/[episode]/+page.svelte
projects/client/src/routes/shows/anticipated/+page.svelte
projects/client/src/routes/shows/popular/+page.svelte
projects/client/src/routes/shows/recommended/+page.svelte
projects/client/src/routes/shows/trending/+page.svelte
projects/client/src/routes/watchlist/+page.svelte

This pull request streamlines the layout and cover image handling across various pages in the client project, improving code organization and maintainability.
- Renamed and moved the `TraktPage` component from the `components/layout` directory to the `sections/layout` directory. This change improves the organization of layout-related components and ensures a more logical structure within the codebase.
- Introduced a new `TraktPageCoverSetter` component to centralize the logic for setting cover images. This component handles cover image setting for both authenticated and public users, promoting code reusability and consistency.
- Replaced direct usage of `CoverImageSetter` in various pages with the new `TraktPageCoverSetter` component, ensuring a unified approach to cover image handling …

fix / consistently use cover image

---

projects/client/src/lib/features/auth/queries/currentUserWatchlistQuery.ts
projects/client/src/lib/features/query/defineQuery.ts
projects/client/src/lib/features/query/useQuery.ts
projects/client/src/lib/requests/models/InvalidateAction.ts

This pull request focuses on improving the consistency and efficiency of query and invalidation handling within the client project.
With this change we'll once again have consistent behavior as with active sessions after first load since data without associated invalidators will stay cached.
- Introduced new utility functions (`queryId`, `schemaId`, `dependencyId`) to generate consistent and predictable IDs for queries, schemas, and dependencies. This standardization improves code readability and reduces the risk of errors caused by inconsistent naming conventions.
- Added an `INVALIDATION_ID` constant and refactored the `InvalidateAction` type to use the `buildInvalidationKey` function for generating invalidation keys. This change centralizes the logic for invalidation key generation, …

feat(query): invalidate queries with associated invalidators only

---

commitlint.config.js
projects/client/src/lib/sections/summary/components/rating/useRatings.spec.ts

This pull request refines the testing approach for the `useRatings` component and updates the commitlint configuration for improved consistency.
- Added `rating` to the list of available categories in the `commitlint.config.js` file. This ensures that commit messages related to rating functionality adhere to the project's standardized naming conventions.
- Replaced `waitForEmission` with more efficient methods in the `useRatings.spec.ts` test file:
- Used `get` to directly check the `isRating` store value, simplifying the test and reducing reliance on asynchronous emissions.
- Replaced `waitForEmission` with `waitForValue` to check the `currentRating` store value, improving test efficiency and reducing the likelihood of flaky tests.
(These changes, like a meticulous detective refining …

test(rating): use value awaiter to eliminate flakiness

---

projects/client/src/lib/components/media/watch-now/WatchNowServiceLogo.svelte
projects/client/src/lib/sections/summary/components/overlay/WatchNowOverlay.svelte

fix(summary): sizing of service logo on poster overlay

---

projects/client/i18n/messages/pl-pl.json
projects/client/i18n/messages/uk-ua.json
projects/client/src/lib/components/buttons/mark-as-watched/MarkAsWatchedButtonProps.ts
projects/client/src/lib/components/buttons/watchlist/WatchlistButtonProps.ts
projects/client/src/lib/components/summary/RatingItem.svelte
projects/client/src/lib/sections/media-actions/mark-as-watched/MarkAsWatchedAction.svelte
projects/client/src/lib/sections/media-actions/watchlist/WatchlistAction.svelte
projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte
projects/client/src/lib/sections/summary/components/rating/RateNow.svelte
projects/client/src/lib/sections/summary/components/summary/SummaryActions.svelte

- Final part to match what I had shown in the prototype earlier.
- Media actions are now placed side by side on smaller sizes.
- Rate now is placed below them if usable.
- Ratings list is smaller on mobile sizes.
- Optimized so that even on an iPhone SE, the buttons fit good enough.
- From here on out, we can start fine tuning more.

feat: responsive media actions

---

projects/client/src/lib/sections/layout/TraktPage.svelte
projects/client/src/lib/sections/summary/components/media/MediaDetails.svelte
projects/client/src/lib/sections/summary/components/media/_internal/CollapsableValues.svelte
projects/client/src/lib/sections/summary/components/media/_internal/DetailsGrid.svelte
projects/client/src/lib/sections/summary/components/media/_internal/WatchNowCategoryServices.svelte

- Increases the content gap on smaller devices.
- Added some space between items in the summary details grid.
Before / after:
Before / after:

fix: content spacing

---

projects/client/src/lib/components/lists/section-list/ShadowList.svelte

This pull request improves the responsiveness of the `ShadowList` component on mobile devices by adjusting the scroll snap behavior.
- Added `@include for-mobile()` media queries to unset `scroll-snap-align` for various elements within the `ShadowList` component. This change disables the scroll snap alignment on mobile screens, providing a smoother and more intuitive scrolling experience on touch devices.
(This adjustment, like a skilled tailor adjusting a garment for a better fit, ensures that the `ShadowList` component adapts seamlessly to different screen sizes. By disabling scroll snap alignment on mobile devices, we prioritize touch-friendly scrolling behavior, enhancing the user experience on smaller screens.)

feat(list): enable free scroll on mobile

---

projects/client/src/lib/sections/lists/watchlist/useWatchlistList.ts

This pull request modifies the default sorting behavior for watchlists to prioritize recently added items.
- Changed the default `sort` parameter in the `typeToQuery` function within `useWatchlistList.ts` from `'rank'` to `'added'`. This change ensures that newly added items appear at the top of the watchlist, providing users with a clearer view of their recently added media.
(This minor adjustment, like a meticulous librarian reorganizing a bookshelf, prioritizes the display of recently added items in the watchlist. By defaulting to the `'added'` sort option, we ensure that users can easily find and access the media they've recently added, improving the overall user experience.)

feat(watchlist): default sort to added

---

projects/client/src/lib/components/dropdown/DropdownList.svelte
projects/client/src/lib/sections/navbar/ProfileButton.svelte

- Similar issue as with the button scaling.
Before/after:
Before/after:

fix(dropdown): scale without transform

---

projects/client/e2e/features/navigate.feature
projects/client/e2e/models/TestId.ts
projects/client/e2e/support/navigate.steps.ts
projects/client/e2e/utils/TestUrlBuilder.ts
projects/client/e2e/utils/prefixPathWithBaseUrl.ts
projects/client/src/lib/sections/summary/components/summary/SummaryTitle.svelte

- Adds 2 simple scenarios to make sure the movie and show summary pages are visible.
- Kept everything in a single scenario to reduce overhead.
Reduced the speed for dramatic purposes:
https://github.com/user-attachments/assets/3b5d2948-191a-4828-8ca8-b88dbad763dd
Still runs fast:

test(e2e): add steps to check media summary pages

---

README.md

Public applications have image access again, limitation remark is now stale.
This pull request includes a small change to the `README.md` file. The change removes the bullet point regarding missing image links from the list of limitations. 
Changes to documentation:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L69-L70): Removed the bullet point about missing image links from the limitations section.

docs(readme): remove image limitation remark

---

projects/client/src/lib/utils/url/buildOAuthLink.spec.ts
projects/client/src/lib/utils/url/buildOAuthLink.ts

This pull request modifies the OAuth authorization URL to include a new query parameter, `hide_email_form=true`, streamlining the authentication process.
- Updated the `buildOAuthUrl` function to append the `hide_email_form=true` query parameter to the OAuth authorization URL. This change instructs the authentication provider to hide the email form during the authorization flow, simplifying the user experience and reducing potential confusion.
- Updated the test cases for `buildOAuthUrl` to reflect the addition of the `hide_email_form=true` query parameter in the expected OAuth authorization URLs. This ensures that the function continues to generate correct URLs with the new parameter.
(This change, like a skilled stagehand removing an unnecessary prop from the set, streamlines the OAuth …

feat(auth): enable passwordless auth flow

---

projects/api/src/contracts/sync/index.ts
projects/client/src/lib/requests/queries/sync/upNextQuery.ts
projects/client/src/lib/requests/queries/sync/upNextQueryNitro.ts
projects/client/src/lib/sections/lists/UpNextList.svelte
projects/client/src/lib/sections/lists/stores/useUpNextEpisodes.ts

This pull request introduces a new, optimized "nitro" version of the "up next" endpoint and updates the client to utilize this enhanced functionality.
- Added `standard` and `nitro` endpoints to the `upNext` router in the API. This provides two versions of the "up next" endpoint: the standard version and the optimized "nitro" version.
- Updated the `upNextRequest` function to use the `standard` endpoint and exported the `mapUpNextResponse` function for reusability.
- Created a new query file, `upNextQueryNitro.ts`, for the `nitro` endpoint, including the request function and query definition.
- Modified the `UpNextList.svelte` component to dynamically determine the type of endpoint to use based on a URL parameter, ensuring the appropriate query is used for fetching data.
- Updated the …

feat(up-next): switch to nitro endpoint

---

projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/components/dropdown/DropdownItem.svelte
projects/client/src/lib/components/link/Link.svelte
projects/client/src/lib/sections/lists/components/CastMemberCard.svelte
projects/client/src/lib/sections/lists/components/MediaSummaryCard.svelte
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
projects/client/src/lib/sections/profile/components/YearToDateLink.svelte

- New styling for links
- Currently this style isn't used anywhere, but see below for an example of what it will look like.
Username link example:

feat(link): use new design for links

---

projects/client/src/lib/components/buttons/popup/PopupMenu.svelte
projects/client/src/lib/components/icons/MoreIcon.svelte

fix: shadow on svg element in safari

---

projects/client/src/lib/components/background/CoverImage.svelte
projects/client/src/lib/components/buttons/Button.svelte
projects/client/src/lib/components/buttons/popup/PopupMenu.svelte
projects/client/src/lib/components/buttons/popup/_internal/createUnderlay.ts
projects/client/src/lib/components/card/CardActionBar.svelte
projects/client/src/lib/components/card/CardCover.svelte
projects/client/src/lib/components/dropdown/DropdownList.svelte
projects/client/src/lib/components/lists/section-list/ShadowList.svelte
projects/client/src/lib/sections/landing/components/TrendingItems.svelte
projects/client/src/lib/sections/navbar/MobileNavbar.svelte
projects/client/src/lib/sections/navbar/Navbar.svelte
projects/client/src/lib/sections/navbar/ProfileButton.svelte
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
projects/client/src/lib/sections/profile-banner/ProfilePageBanner.svelte
projects/client/src/routes/+layout.svelte
projects/client/src/style/index.ts
projects/client/src/style/layers/index.css

This pull request standardizes the use of `z-index` values across various components by introducing new CSS custom properties and refactoring existing styles.
- Added a new CSS file, `projects/client/src/style/layers/index.css`, to define custom properties for `z-index` values. These properties are categorized into base layers, interactive layers, and system layers, providing a clear and organized system for managing visual hierarchy.
- Updated several components to use the new `z-index` custom properties, ensuring consistency and maintainability in managing the visual stacking order of elements.
- Components updated include `CoverImage`, `Button`, `PopupMenu`, `CardActionBar`, `CardCover`, `DropdownList`, `MobileNavbar`, `Navbar`, and `SearchInput`.
- Refactored the `DropdownList` …

feat / define layering system

---

projects/client/src/lib/components/text/ClampedText.svelte

fix: increase gap for more button when text is clamped

---

projects/client/src/lib/sections/lists/social/SocialActivityCard.svelte

fix(social): improve username readability on light covers

---

projects/client/src/lib/requests/queries/users/episodeHistoryQuery.ts
projects/client/src/lib/requests/queries/users/movieHistoryQuery.ts
projects/client/src/lib/sections/lists/stores/useRecentlyWatchedList.ts

- The recently watched lists will now show the last 25 items, the `view all` variants will show the last 100 items.

fix(watched): do not use date range for recently watched items

---

projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/sections/lists/components/EpisodeCard.svelte
projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
projects/client/src/lib/sections/lists/social/SocialActivityCard.svelte

This pull request standardizes CSS class names and improves the styling for card components.  The primary changes involve renaming title and subtitle classes and updating their associated styles for consistency.
* **`EpisodeCard.svelte`**: The class names `.episode-card-title` and `.episode-card-subtitle` have been renamed to `.trakt-card-title` and `.trakt-card-subtitle`, respectively.  All instances of these classes within the file have been updated to reflect the new names.
* **`MediaItemCard.svelte`**:  Similarly, `.media-title` and `.media-subtitle` have been renamed to `.trakt-card-title` and `.trakt-card-subtitle`.  The old styles associated with the previous class names have been removed.
* **`CardFooter.svelte`**: New styles have been added for `.trakt-card-title` and …

improve / card title and subtitle styling and ensure username does not overflow

---

projects/client/src/lib/components/dropdown/DropdownList.svelte
projects/client/src/lib/components/lists/section-list/ShadowList.svelte
projects/client/src/routes/+layout.svelte

- Safari (╯°□°)╯︵ ┻━┻
- Scrollbars never became visible.
- Dropdowns were hidden under the section lists.
I removed the `opacity:0`, which causes safari to be buggy when it comes to displaying hiding scrollbars. Example:
https://github.com/user-attachments/assets/4929838c-f989-484d-9904-095a4e9e7cf3
So for now, the overflow-x on the lists is set on a hover.
Dropdown fix:
Before/after:

fix: scrollbars in safari

---

projects/client/src/lib/guards/_internal/RenderForDevice.svelte

This pull request modifies the `RenderForDevice.svelte` component to enhance its device-specific rendering logic. The primary change involves adjusting the CSS rule for `trakt-render-for` to improve how elements are displayed on different devices.
* **`RenderForDevice.svelte`**: The `trakt-render-for` CSS rule has been modified.  It now defaults to `display: none`, effectively hiding elements by default.  For elements that *do not* have classes prefixed with "render-for-", the rule is overridden with `display: contents!important`.  This ensures that only elements explicitly intended for specific devices are shown, improving the accuracy of device-specific rendering and preventing unintended display of content.
(This update, like a detective carefully examining a piece of evidence, refines …

fix: initialize rendering with display none

---

projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte

This pull request refines the `SearchInput.svelte` component to improve the user interface and user experience.  The key changes enhance the visual feedback and interactivity of the search input.
* **Cursor Pointer on Search Icon**: The `.trakt-search-icon` class now includes `cursor: pointer`. This provides a clear visual cue to the user that the icon is clickable, improving discoverability of the icon's click functionality.
* **Transition Property Update**: The transition properties have been updated to include `opacity`. This results in smoother and more visually appealing transitions when the search input gains or loses focus.
* **Opacity Adjustment on Focus**: The opacity of the search input elements is now dynamically adjusted based on the focus state.  The opacity is set to `0` …

feat(search): hide input control if not focused

---

projects/client/src/lib/sections/summary/EpisodeSummary.svelte

This pull request enhances the episode summary section by integrating a related list component. This addition provides users with relevant recommendations and improves the overall viewing experience.
* **`RelatedList` Import**: The `RelatedList` component has been imported into the `EpisodeSummary.svelte` file. This component displays a list of related shows, offering viewers additional content recommendations based on the episode they are currently viewing.
* **`RelatedList` Integration**: The `RelatedList` component has been added to the episode summary section. This integration ensures that users can easily discover and explore related shows, enhancing their viewing experience and encouraging further content exploration within Trakt Lite.
(This update, like a detective uncovering …

feat(summary): add related shows on episode pages

---

projects/client/src/lib/sections/media-actions/mark-as-watched/MarkAsWatchedAction.svelte
projects/client/src/lib/sections/media-actions/watchlist/WatchlistAction.svelte
projects/client/src/lib/sections/media-actions/watchlist/useIsWatchlisted.ts
projects/client/src/lib/sections/media-actions/watchlist/useWatchlist.spec.ts
projects/client/src/lib/sections/media-actions/watchlist/useWatchlist.ts

This pull request introduces enhancements to the watchlist functionality in the media actions section and includes code refactoring for improved maintainability.
* **`MarkAsWatchedAction.svelte`**: The `MarkAsWatchedAction.svelte` component now utilizes the new `useIsWatchlisted` utility function. This ensures that an item is not accidentally marked as watched if it is still on the user's watchlist, preventing unintended changes to their watch history.
* **`useIsWatchlisted.ts`**: A new utility function, `useIsWatchlisted`, has been added to determine if a media item is currently in the user's watchlist. This function provides a centralized and reusable way to check the watchlist status of media items.
* **`useWatchlist.ts`**: The `useWatchlist` function has been refactored to use the new …

feat / allow user to mark as watched if item is watchlisted

---

projects/client/src/lib/components/buttons/ActionButton.svelte
projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/components/icons/CaretLeftIcon.svelte
projects/client/src/lib/components/icons/CaretRightIcon.svelte

This pull request introduces several styling and layout adjustments to button, card footer, and icon components within the `projects/client/src/lib/components` directory. The changes primarily focus on refining sizes, margins, and SVG dimensions to enhance visual consistency and overall appearance.
* **`ActionButton.svelte`**: The size of action buttons has been increased slightly from `var(--ni-36)` to `var(--ni-40)`. Additionally, the scale and margin for the small size variant have been adjusted to maintain visual balance and proportion.
* **`CardFooter.svelte`**: The margin-top value for the `trakt-card-footer-information` class has been updated from `var(--ni-neg-2)` to `var(--ni-neg-4)`. This minor adjustment refines the spacing within the card footer, improving the visual layout.
* …

feat(ds): update action button size to 40 globally and 32 within footer

---

projects/client/src/lib/sections/navbar/Navbar.svelte

Small visual fix; when navbar overlaps cards, the rounding will be the same. Example of my slight annoyance:

fix(navbar): match card border radius

---

commitlint.config.js
projects/client/src/lib/components/dropdown/DropdownItem.svelte
projects/client/src/lib/components/link/Link.svelte
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
projects/client/src/lib/sections/summary/components/media/MediaSummaryItem.svelte
projects/client/src/lib/utils/actions/mobileAppleDeviceTriggerHack.spec.ts
projects/client/src/lib/utils/actions/mobileAppleDeviceTriggerHack.ts

This pull request streamlines the codebase and improves the handling of mobile Apple devices, particularly addressing issues related to Safari.
* **`retrigger` Property Removal**: The `retrigger` property has been removed from several components, including `DropdownItem.svelte`, `Link.svelte`, `SearchInput.svelte`, and `MediaSummaryItem.svelte`. This removal simplifies the code and reduces unnecessary complexity.
* **`mobileAppleDeviceTriggerHack` Update**: The `mobileAppleDeviceTriggerHack` function has been updated to specifically target `HTMLAnchorElement` instead of the more general `HTMLElement`. This change improves the precision of the function and ensures that it only affects anchor elements. Additionally, a navigation check using `beforeNavigate` has been added to ensure that …

fix(safari): navigation retriggering randomly

---

projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte

fix(search): search width in non floating navbar

---

projects/client/src/lib/components/lists/_internal/ListHeader.svelte

fix(list): ellipse list headers

---

projects/client/src/lib/sections/lists/components/list-summary/ListPreview.svelte
projects/client/src/lib/sections/summary/components/lists/Lists.svelte
projects/client/src/routes/lists/official/[id]/+page.svelte
projects/client/src/routes/users/[user]/lists/[list]/+page.svelte

- Adds some missing derivations.
- Will get some follow-ups:
- List scroll positions:
- not all ID's are correct.
- restoring scroll history seems to use the wrong ID.
- Season lists seem to have a similar issue.

fix: add missing derivations

---

projects/client/src/lib/sections/summary/EpisodeSummary.svelte
projects/client/src/lib/sections/summary/components/summary/SummaryActions.svelte

- The episode summary actions now match the media summary actions.
- Ideally we do a follow up on this. The `SummaryActions` component makes assumptions it shouldn't make:
- Either on consumer side the actions are already placed in their own container and sized properly.
- Or we omit the design where on large tablets the `watchlist` and `mark as watched` buttons are sized 50/50.
Before:
After:

fix(summary): responsiveness of episode summary actions

---

projects/client/src/lib/components/buttons/popup/PopupMenu.svelte

This pull request refines the styling of the `PopupMenu` component to improve positioning and enhance the touch experience.
* **Relative Positioning**: The `.trakt-popup-menu-button` class now includes `position: relative`. This ensures that any child elements within the button are positioned correctly relative to the button itself, preventing unexpected overlaps or misalignments.
* **Touch Target Enhancement**: A new `for-touch` style has been added to the component. This style introduces a pseudo-element that increases the touch target area for the popup menu button, making it easier to interact with on touch devices. The pseudo-element is absolutely positioned, centered using CSS transforms, and scaled to 175% of the original element's size, providing a larger and more comfortable …

feat(popup): increase tappable area for touch input

---

projects/client/src/lib/components/summary/RatingItem.svelte
projects/client/src/lib/components/summary/RatingList.svelte
projects/client/src/lib/components/summary/_internal/getDisplayableRatings.spec.ts
projects/client/src/lib/components/summary/_internal/getDisplayableRatings.ts
projects/client/src/lib/requests/_internal/mapToMediaRating.ts
projects/client/src/lib/requests/models/MediaRating.ts
projects/client/src/lib/utils/formatting/number/toRottenTomatoRating.spec.ts
projects/client/src/lib/utils/formatting/number/toRottenTomatoRating.ts
projects/client/src/lib/utils/formatting/number/toVotesBasedRating.spec.ts
projects/client/src/lib/utils/formatting/number/toVotesBasedRating.ts
projects/client/src/mocks/data/summary/episodes/silo/mapped/EpisodeSiloRatingsMappedMock.ts
projects/client/src/mocks/data/summary/episodes/silo/response/EpisodeSiloRatingsResponseMock.ts
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticRatingsMappedMock.ts
projects/client/src/mocks/data/summary/movies/heretic/response/MovieHereticRatingsResponseMock.ts
projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloRatingsMappedMock.ts
projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloRatingsResponseMock.ts

- Apparently we can have empty ratings, but still have vote counts.
Before:
After:

fix(rating): ignore vote count if there is no rating

---

projects/client/src/lib/sections/navbar/MobileNavbar.svelte

- Fixes https://github.com/trakt/trakt-lite/issues/289
- Removes the labels from the mobile navbar
- We'll not have to worry about making sure translations would always fit.
- These buttons are clear enough; if not:
- Pages load quite fast, after a single tap users know what the button does.
- If the icons aren't clear enough, we can improve on that also.
Before:
After:

fix(navbar): mobile navbar without labels

---

projects/client/src/lib/sections/lists/progress/useUpNextExperiment.ts

This pull request refines the handling of the "Up Next" feature in the `useUpNextExperiment.ts` file by introducing constants and simplifying the type toggling logic.
* **Constants for Default Value and Storage Key**:
* `DEFAULT_UP_NEXT_TYPE`: A new constant, `DEFAULT_UP_NEXT_TYPE`, has been introduced with the value 'nitro' to represent the default type for the "Up Next" feature.
* `UP_NEXT_STORAGE_KEY`: The storage key for the "Up Next" type has been updated to 'up-next-type-v2' to distinguish it from previous versions.
* **Simplified Type Toggling**:
* `UP_NEXT_TOGGLE_TYPE_MAP`: A new constant, `UP_NEXT_TOGGLE_TYPE_MAP`, has been added to map between 'standard' and 'nitro' types, simplifying the toggling logic.
* `toggle` Function Update: The `toggle` function now utilizes the …

feat(up-next): enable nitro by default

---

projects/client/src/lib/sections/media-actions/mark-as-watched/MarkAsWatchedAction.svelte
projects/client/src/lib/sections/media-actions/watchlist/WatchlistAction.svelte

This pull request streamlines the `MarkAsWatchedAction.svelte` and `WatchlistAction.svelte` components by removing unused imports, properties, and unnecessary `onMount` subscriptions.
* **`MarkAsWatchedAction.svelte`**:
* The `onMount` import and the `onAction` property have been removed, as they were not being used in the component.
* The `onMount` subscription, which previously called `onAction` when `isMarkingAsWatched` changed, has been eliminated. This simplification removes unnecessary code and improves the component's efficiency.
* **`WatchlistAction.svelte`**:
* Similar to the `MarkAsWatchedAction` component, the `onMount` import, `onAction` property, and the corresponding `onMount` subscription have been removed. This cleanup streamlines the code and removes unnecessary …

fix: remove strange action delegation

---

.github/workflows/ci.yml
projects/client/e2e/world.ts

Always use the headless version of user agents in E2E tests.

chore(e2e): strip headless from user agent

---

projects/client/i18n/messages/de-de.json
projects/client/i18n/messages/en.json
projects/client/i18n/messages/es-es.json
projects/client/i18n/messages/es-mx.json
projects/client/i18n/messages/fr-ca.json
projects/client/i18n/messages/fr-fr.json
projects/client/i18n/messages/it-it.json
projects/client/i18n/messages/ja-jp.json
projects/client/i18n/messages/nl-nl.json
projects/client/i18n/messages/pl-pl.json
projects/client/i18n/messages/pt-br.json
projects/client/i18n/messages/ro-ro.json
projects/client/i18n/messages/uk-ua.json
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte

Pending design checks:
- Use a max width after all; search can get too big on desktop otherwise.
- Use a background for the search icon on non-scrolled mobile view.
- Updated design for search input.
- New placeholder text
- Ellipsed placeholder text
- Desktop:
- Increased max width
- Only show outline when scrolled
- Mobile:
- Should look the same in non-scrolled version
- When scrolled, background is removed
before/after:
before/after:
before/after:
before/after:

feat(navbar): new search input design

---

projects/client/src/lib/sections/summary/components/media/MediaMetaInfo.svelte

- Could overflow in some languages
Before:
After:

fix(summary): meta tags overflow

---

projects/client/src/lib/sections/summary/components/rating/constants.ts
projects/client/src/lib/sections/summary/components/rating/mapRatingToSimpleRating.spec.ts
projects/client/src/lib/sections/summary/components/rating/mapRatingToSimpleRating.ts

- Minor tweaks to ratings mappings:
- 9 & 10 are not both mapped to ❤️
- 6 is no longer considered bad

chore(rating): tweaked ratings mapping

---

deno.lock
projects/client/package.json
projects/client/src/app.d.ts
projects/client/src/lib/features/filters/useFilter.ts
projects/client/src/lib/requests/models/FilterParams.ts
projects/client/src/lib/requests/queries/recommendations/recommendedMoviesQuery.ts
projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
projects/client/src/lib/sections/lists/drilldown/DrillableMediaList.svelte
projects/client/src/lib/sections/lists/recommended/RecommendedList.svelte
projects/client/src/lib/sections/lists/recommended/RecommendedPaginatedList.svelte
projects/client/src/lib/sections/lists/recommended/extractWatchWindowParam.ts
projects/client/src/lib/sections/lists/recommended/useRecommendedList.ts
projects/client/src/lib/utils/constants.ts
projects/client/src/lib/utils/url/UrlBuilder.ts

This pull request introduces several changes to enhance the filter functionality and improve the handling of recommended lists. Key improvements include dependency updates, modified filter parameters, and better handling of the watch window parameter.
* **`useFilter.ts` Refinement**: The `filterMap`'s return value in `useFilter.ts` now defaults to an empty object instead of `undefined` when the filter value is absent. This seemingly small change can prevent some unexpected null pointer exceptions down the line. It's like finding a tiny crack in the wall before the whole building collapses, eh?
* **`FilterParams` Evolution**: The `FilterParams` type definition has been updated to use `DeepPartial` for greater flexibility. Plus, the `watch_window` parameter has been added, giving users a …

feat / expose recommended watch_window param to enable fine-tuning 

---

projects/client/src/app.html

This pull request fortifies the application's defenses with Content Security Policy (CSP) updates and introduces Hotjar analytics to gain insights into user behavior.
* **`script-src` and `script-src-elem` Fortification**: The `script-src` and `script-src-elem` directives have been updated to permit scripts from `https://*.contentsquare.net` and `https://static.hj.contentsquare.net`. We're opening the gates, but only to trusted allies.
* **`connect-src` Expansion**: The `connect-src` directive has been broadened to include `https://*.contentsquare.net`, `https://*.hotjar.com`, and `https://*.hotjar.io`, specifically for those elusive WebSocket connections. We need to hear what they're saying, you know?
* **`frame-src` Authorization**: The `frame-src` directive now allows frames from …

feat(ds): integrate hotjar for UX guys

---

projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/sections/lists/components/CastMemberCard.svelte
projects/client/src/style/layout/index.css
projects/client/src/style/sizing/index.css

This pull request focuses on enhancing the consistency and readability of card components in the client project.
* **`CardFooter.svelte`**:
* The `gap` property has been adjusted to use the newly introduced `--gap-micro` variable. This is a subtle shift, but it's all about those small details, isn't it?
* Font sizes for primary and secondary text elements have been bumped up from `var(--ni-11)` to `var(--ni-12)`. A touch of clarity, making those words easier to read, like a sharp image in a blurry world.
* **`index.css` (Sizing)**:
* A new spacing variable, `--gap-micro`, has been added with a value of `var(--ni-2)`. This gives us finer-grained control over layout spacing, allowing for more precise adjustments.
* **`CastMemberCard.svelte`**:
* Custom class names `actor-name` and `small …

fix / improve card readability and align actors

---

projects/android-tv/.idea/misc.xml
projects/android-tv/app/src/main/java/tv/trakt/app/MainActivity.kt
projects/android-tv/app/src/main/java/tv/trakt/app/WebAppInterface.kt

- Adds basic support for opening deep links in the android wrapper.
- This is very basic support :P We should later on style the dialog properly.
Usage in Lite would be like:
````
StreamOnAndroid.open(
"Netflix",
"nflx://www.netflix.com/watch/81131575?source=topshelf",
);
````
Test with an available and unavailable app:
https://github.com/user-attachments/assets/bae3e1d7-013d-4911-b46d-0130a7b44785
https://github.com/user-attachments/assets/06597f68-935a-44f1-9810-077e414c2286

feat(android-tv): add callback for streamon deep links

---

projects/client/src/lib/features/auth/handle.ts

- Always use the host for the redirect uri on exchange & refresh.

fix(auth): only use host header for the redirect uri

---

projects/client/src/lib/sections/lists/components/EpisodeItemCard.svelte

This pull request introduces updates to the `EpisodeItemCard.svelte` component, enhancing its functionality and improving its user interface. The changes primarily focus on adding conditional rendering for episode-specific details and incorporating a new tag component.
* **Added `AirDateTag` for upcoming episodes:** Introduced a new `AirDateTag` component that displays the air date for episodes with the `upcoming` variant. For other variants, the existing `DurationTag` is used. (`projects/client/src/lib/sections/lists/components/EpisodeItemCard.svelte`, [[1]](diffhunk://#diff-b8fd52c4c90d3cacc2bdf192bf88420bd53bd362301d3684dc31595485738dcaR9-R16) [[2]](diffhunk://#diff-b8fd52c4c90d3cacc2bdf192bf88420bd53bd362301d3684dc31595485738dcaR40-R48)
* **Conditional rendering for episode title …

feat / episode improvements

---

projects/client/src/lib/components/summary/RatingList.svelte

- @kevincador had a good remark; external ratings are quite close to each other. I.e. the gap between external ratings and the inner gap between logo/rating is the same. Especially annoying when there is no rating. This increases the distance between ratings.
Before:
After:

fix(summary): less clamped external ratings

---

projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte

- Remove old hover styling
Ignore the non-pointer cursor, side effect of recording.
Before:
https://github.com/user-attachments/assets/7b671e22-3a9a-4305-a51a-5f6996fbccd8
After:
https://github.com/user-attachments/assets/a6efc78b-3258-48b4-a764-17e5cf818047

fix(search): remove broken hover effect in search results

---

projects/client/src/lib/components/card/CardCover.svelte
projects/client/src/lib/components/card/CardCoverProps.ts
projects/client/src/lib/sections/landing/components/TrendingItems.svelte
projects/client/src/lib/sections/lists/anticipated/AnticipatedListItem.svelte
projects/client/src/lib/sections/lists/components/ActivityCard.svelte
projects/client/src/lib/sections/lists/components/ActivitySummaryCard.svelte
projects/client/src/lib/sections/lists/components/DefaultMediaItem.svelte
projects/client/src/lib/sections/lists/components/EpisodeCard.svelte
projects/client/src/lib/sections/lists/components/EpisodeCardProps.ts
projects/client/src/lib/sections/lists/components/EpisodeItemCard.svelte
projects/client/src/lib/sections/lists/components/MediaCard.svelte
projects/client/src/lib/sections/lists/components/MediaCardProps.ts
projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
projects/client/src/lib/sections/lists/components/MediaSummaryCard.svelte
projects/client/src/lib/sections/lists/social/SocialActivityItem.svelte
projects/client/src/lib/sections/lists/streaming/StreamingListItem.svelte
projects/client/src/lib/sections/lists/trending/TrendingListItem.svelte
projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte

This pull request undertakes a significant act of purification, standardizing property names across various components. The many `badges` and `tags` are now unified under the singular banners of `badge` and `tag`. A linguistic cleansing, ensuring that the very vocabulary of these components speaks a consistent truth.
* The pluralistic reigns of `badges` and `tags` have ended in `CardCoverProps` and `MediaCardProps`. Long live the singular `badge` and `tag`, ensuring a harmonious nomenclature across the digital landscape of components.
* Across `CardCover.svelte`, the many instances of `badges` and `tags` have been meticulously replaced with their singular counterparts. Markup, styles, conditional rendering – all now sing the same, unified tune.
* This linguistic reformation extends to …

refactor / cleanup card restyling aftermath

---

deno.lock
projects/client/package.json
projects/client/src/lib/requests/models/FilterParams.ts
projects/client/src/lib/requests/queries/recommendations/recommendedMoviesQuery.ts
projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
projects/client/src/lib/sections/lists/recommended/RecommendedList.svelte
projects/client/src/lib/sections/lists/recommended/RecommendedPaginatedList.svelte
projects/client/src/lib/sections/lists/recommended/extractMinYearParam.ts
projects/client/src/lib/utils/constants.ts
projects/client/src/lib/utils/url/UrlBuilder.ts

This pull request grants us a finer degree of temporal control over the recommended content, introducing the `min_year` filter.
* **Filter Parameter Expansion**: The `FilterParams` type now accommodates the `min_year`, allowing us to specify the dawn of an era for our recommendations. And the queries for `recommendedMoviesQuery` and `recommendedShowsQuery` now keenly observe this `min_year` parameter.
* **Navigating the Temporal Stream**: A new tool, `extractMinYearParam`, has been forged to pluck the `min_year` from the chaotic currents of URL search parameters, with a default set to the nostalgic year of 1990. The `UrlBuilder` now also recognizes and sanitizes this temporal marker.
* **A Foundation in Time**: A constant, `RECOMMENDED_DEFAULT_MIN_YEAR`, has been established, anchoring …

feat(recommended): expose watch_window param to play around

---

projects/client/src/lib/components/icons/RateIcon.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/SentimentComment.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/UserRatingIcon.svelte
projects/client/src/lib/sections/summary/components/rating/UserRating.svelte
projects/client/src/lib/sections/summary/components/rating/_internal/RateActionButton.svelte

- Switches to the new design for the rate buttons.
Before:
After:

feat(rating): new rating icons

---

projects/client/src/lib/requests/queries/sync/upNextQuery.ts

This pull request refines the `mapUpNextResponse` function in `upNextQuery.ts` to improve data mapping and ensure consistency between show and episode entries.
* [`projects/client/src/lib/requests/queries/sync/upNextQuery.ts`](diffhunk://#diff-5088ccb5d851e956dd8c3522301d26c981bd3c386957a9c63beb271837340973L55-R61): Updated `mapUpNextResponse` to use `mapToShowEntry` and `mapToEpisodeEntry` for clearer separation of concerns. Additionally, the `episode.runtime` is now set to the `show.runtime` if it is undefined, ensuring runtime consistency between the show and its episodes.

fix(up-next): default to show runtime when episode runtime is null

---

projects/client/src/lib/features/navigation/_internal/focusSomething.ts

- Ran into this one when testing the webview reload:
- On a reload, if movies was the active page, it would still be the active link, but the first item in the navbar would be focused instead.
- This updates `focusSomething` to check active links first.
Before:
https://github.com/user-attachments/assets/b3f21aef-6b58-4123-b33b-7c3788e3a238
After:
https://github.com/user-attachments/assets/17229772-a222-4da8-b914-83ab27269b91

feat(navigation): prioritize active links when focusing something

---

commitlint.config.js
deno.lock
projects/client/package.json
projects/client/src/lib/components/gestures/SwipeX.svelte
projects/client/src/lib/components/icons/MarkAsWatchedIcon.svelte
projects/client/src/lib/sections/lists/progress/EpisodeProgressItem.svelte
projects/client/src/lib/sections/media-actions/mark-as-watched/MarkAsWatchedSwipeIndicator.svelte

This pull request introduces a swipe gesture feature for marking episodes as watched in the client application. It includes the addition of a new `SwipeX` component, integration of gesture-based interactions in the episode progress list, and supporting UI updates. Below are the most important changes grouped by theme:
* Added a new `SwipeX` component in `projects/client/src/lib/components/gestures/SwipeX.svelte`, which utilizes the `@use-gesture/vanilla` library to handle swipe gestures. It includes logic for detecting swipe direction, progress, and triggering actions based on thresholds.
* Integrated the `SwipeX` component into `EpisodeProgressItem.svelte` to enable swipe gestures for marking episodes as watched. The swipe gesture is configured to trigger the `markAsWatched` action when …

feat / mark as watched gesture for up-next

---

projects/client/src/lib/features/navigation/NavigationProvider.svelte
projects/client/src/lib/features/navigation/useNavigation.ts

- The redirect with the param removal is no longer necessary; it even breaks the global param

fix(params): do not remove navigation param

---

projects/client/src/lib/components/media/card/PortraitCard.svelte
projects/client/src/lib/sections/lists/components/EpisodeCard.svelte
projects/client/src/lib/sections/lists/components/MediaCardProps.ts
projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
projects/client/src/lib/sections/lists/drilldown/MediaList.svelte
projects/client/src/lib/sections/lists/utils/mediaCardWidthResolver.ts
projects/client/src/lib/sections/lists/utils/mediaListHeightResolver.ts
projects/client/src/lib/stores/useDefaultCardVariant.ts
projects/client/src/routes/search/+page.svelte
projects/client/src/style/layout/index.css

This pull request introduces a new "portrait" card variant across the media card components, updates the default card variant logic, and refactors related styles and utilities. The key changes include replacing the "poster" variant with "portrait," adding dynamic default variant selection based on navigation type, and updating the associated styles and utilities to align with the new naming convention.
* Replaced the "poster" variant with "portrait" across all relevant components, including `PortraitCard.svelte` and `MediaItemCard.svelte`. Updated conditional rendering logic to handle "portrait" and "landscape" variants. (`[[1]](diffhunk://#diff-3a81fd0d523a8e3a3686bdec98474cd8d46912d9c99ef36f2be2adc73d633362L9-R11)`, `[[2]](diffhunk://#diff-0a05c68a4ddcdfdac5b8747483b7df66a5db38151d95bcf6 …

feat / use landscape cards when navigating via dpad

---

projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
projects/client/src/lib/sections/lists/drilldown/MediaList.svelte
projects/client/src/lib/sections/lists/utils/mediaListHeightResolver.ts
projects/client/src/lib/stores/useDefaultCardVariant.ts

This pull request refactors how default card variants are determined and simplifies the media list height resolver logic. The changes ensure that the `type` parameter is consistently passed to relevant functions, improving flexibility and maintainability.
* [`projects/client/src/lib/stores/useDefaultCardVariant.ts`](diffhunk://#diff-b2a9c5997e08cb10e4fd07ddd5d56e9a49140951c4fa3cf9c71eaa44343c5dbbL4-R11): Updated `useDefaultCardVariant` to accept a `type` parameter and added logic to return `'landscape'` for `'episode'` types.
* [`projects/client/src/lib/sections/lists/components/MediaItemCard.svelte`](diffhunk://#diff-0a05c68a4ddcdfdac5b8747483b7df66a5db38151d95bcf6dfa3b568e6401190L28-R28): Modified the `defaultVariant` to use the updated `useDefaultCardVariant` function with the `type` …

fix(card): correctly compute default card varian

---

projects/client/src/lib/components/card/_internal/dPadTrigger.ts

- For some reason the event code was `MailReply`...

fix(navigation): d-pad trigger

---

projects/client/src/lib/features/filters/_internal/constants.ts
projects/client/src/lib/features/filters/_internal/genres.ts

- Uses a more condensed list of genres.
- I left out things that either seem redundant or not genre-like. The following items are left out:
````
'game-show',
'home-and-garden',
'mini-series',
'special-interest',
'sporting-event',
'talk-show',
'none',
'news',
'donghua',
'music',
'short',
'soap',
'reality'
````

feat(filter): use a more condensed lists of genres for filtering

---

projects/client/src/lib/components/buttons/watchlist/WatchlistButton.svelte
projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte

- When in d-pad mode, the movie & show summary pages now have the watchlist button
Before:
After:

feat(summary): add watch list button when navigating with d-pad

---

projects/client/src/lib/sections/lists/popular/PopularListItem.svelte

- `remove from list` is available again on listed items
Before:
After:

fix(list): use correct popup actions for media items in lists

---

.github/actions/setup-deno/action.yml
.github/workflows/ci.yml

This pull request updates the CI workflow by introducing caching for Deno dependencies. The caching mechanism is added to improve build performance by reusing previously downloaded dependencies.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR69-R78): Added a step to cache Deno dependencies using `actions/cache@v4`. The cache includes paths `~/.cache/deno` and `~/.deno`, with a key based on the operating system and a hash of `deno.json` and `deno.lock` files. Restore keys are also specified for fallback. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR69-R78) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR159-R168)

ci: enable deno dependency cache

---

projects/client/src/lib/components/card/Card.svelte

- New card focus state when navigating using the d-pad.
- Matches the designed version more closely.
- No zoom effect (for now)
- Ideally we do a follow up to do this without scaling, even if we want to keep it without zoom.
- With the scaling approach the margins/paddings are not equal.
- Using the scaling approach with a bigger zoom effect leads to cards that are too tiny and gaps between them too large.
Before:
https://github.com/user-attachments/assets/352f26f9-d74a-4066-b60b-a81f4e991ad2
After:
https://github.com/user-attachments/assets/9bd8687e-7a63-42c9-9d9f-2898a2354b46

feat(card): new focus effect when navigating with d-pad

---

projects/client/src/lib/requests/_internal/createAuthenticatedFetch.ts

- No longer rely on checking for expired token. If we send an Authorization header, and get a 401 back, we reload.

fix(auth): always try a reload on authentication fail

---

projects/client/src/lib/sections/summary/EpisodeSummary.svelte
projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte

- Gets rid of unusable clutter in summary pages (i.e. no more details section).
Before:
After:

fix(summary): hide details when navigating with d-pad

---

projects/client/src/lib/features/navigation/_internal/focusAndScrollIntoView.spec.ts
projects/client/src/lib/features/navigation/_internal/focusAndScrollIntoView.ts
projects/client/src/lib/features/navigation/_internal/handleListNavigation.ts

- When scrolling through lists, the scroll behavior is smooth.
- When navigating to the top or bottom list, the page is scrolled to the top/bottom respectively.
Before:
https://github.com/user-attachments/assets/6f98a0fd-225a-40b5-a3d5-a2b46f0ac419
After:
https://github.com/user-attachments/assets/68b24c43-dfd6-4d89-938a-bb5e5175ac7c

fix(navigation): scroll when navigation to lists

---

projects/client/src/lib/sections/lists/components/VideoItem.svelte

- On android tv, open extras in native app.
👀 Example 👀
Before:
https://github.com/user-attachments/assets/c35142f6-2ed4-4332-bd97-ad899c670e90
After:
https://github.com/user-attachments/assets/eb4e4d28-1403-4137-b7ae-020eaa54622f

feat(android-tv): open extras in native app

---

projects/client/src/lib/requests/queries/search/searchQuery.ts

This pull request introduces experimental parameters for the search functionality in the `searchQuery.ts` file. The changes aim to enhance the search engine configuration by adding a new parameter group and integrating it into the search request.
* [`projects/client/src/lib/requests/queries/search/searchQuery.ts`](diffhunk://#diff-21b94df79ee224ff189ab19d0165fd42166981fa2e53d0986d2d2bfa5c32271cR38-R41): Introduced a new constant `EXPERIMENTAL_PARAMS` containing experimental search engine parameters (e.g., `engine: 'typesense'`). This is intended to enable testing of alternative search configurations.
* [`projects/client/src/lib/requests/queries/search/searchQuery.ts`](diffhunk://#diff-21b94df79ee224ff189ab19d0165fd42166981fa2e53d0986d2d2bfa5c32271cR54): Integrated `EXPERIMENTAL_PARAMS` …

feat(search): default to typesense engine

---

projects/client/src/lib/components/background/CoverImage.svelte
projects/client/src/lib/components/background/TraktCoverImage.svelte
projects/client/src/style/theme/modes.scss

feat(cover): update designs such that focus is more on main content

---

projects/client/src/routes/_design_system/_internal/table/FormatSection.svelte
projects/client/src/routes/_design_system/_internal/table/Table.svelte
projects/client/src/routes/_design_system/_internal/table/TableBody.svelte
projects/client/src/routes/_design_system/_internal/table/TableCell.svelte
projects/client/src/routes/_design_system/_internal/table/TableHead.svelte
projects/client/src/routes/_design_system/_internal/table/TableRow.svelte
projects/client/src/routes/_design_system/_internal/table/index.ts
projects/client/src/routes/_design_system/formatting/dates/+page.svelte
projects/client/src/routes/_design_system/formatting/numbers/+page.svelte

Introduces a set of internal table components for the design system.
- Adds FormatSection, Table, TableBody, TableCell, TableHead, and TableRow components.
- Implements number formatting examples page, showcasing toHumanNumber and toPercentage utilities.
- Updates date formatting examples page, utilizing the new table components to display formatting outputs.

feat / internal table components and formatting examples

---

projects/client/src/lib/features/query/QueryClientProvider.svelte
projects/client/src/lib/features/query/_internal/createPersister.ts
projects/client/src/routes/+layout.svelte

- No indexed db on TV. Likely culprit for slowness on TV.
- Could not test in dev env; can't login on preview build running on actual android tv device.
All queries are fine (e.g. they're not taking ages):
Slowdown seems to be caused by indexed db operations:

perf(tv): disable idb on tv

---

projects/client/src/lib/utils/formatting/date/LOCALE_MAP.ts

- Swedish date formats were wrong. Woops 😅
Before:
After:

fix(formatter): swedish date formatting

---

projects/client/src/lib/features/search/SearchInput.svelte
projects/client/src/lib/sections/navbar/ProfileButton.svelte
projects/client/src/lib/sections/profile-banner/ProfilePageBanner.svelte

Suppresses specific elements from heatmap tracking instead of using a global suppression setting, global text suppression ruined the CSS styles.

feat / suppresses targeted areas from heatmap

---

projects/client/src/lib/requests/_internal/mapToStreamingServices.ts
projects/client/src/lib/requests/queries/episode/streamEpisodeQuery.ts
projects/client/src/lib/requests/queries/movies/streamMovieQuery.ts
projects/client/src/lib/requests/queries/shows/streamShowQuery.ts

- Reverts the android deeplinks. They seem worse than the direct links

revert: "feat(tv): use android deep links"

---

projects/client/src/lib/components/background/CoverImage.svelte

This pull request delves into the visual presentation of the `CoverImage` component, seeking to fine-tune its appearance for various cover types and enhance the underlying structure.
* The gradient background, that subtle wash of color that hints at the world beyond the frame, has been alchemized. Now set at a precise 180-degree angle, its color mixing logic has been refined, aiming for smoother, more evocative transitions. Like the slow fade of a memory.
* The `backdrop-filter`, that subtle blurring effect, makes a conditional return for non-main cover types. A touch of visual separation, with a fallback to `unset` on smaller screens, like a whispered secret that fades with distance.
* And for the main cover types, a new rule emerges: in the cramped confines of mobile views, the …

feat(cover): improved contrast for light covers

---

.github/actions/setup-deno/action.yml
.github/workflows/ci.yml

Disables PostHog telemetry within Paraglide.js during CI builds.
- Patches the Paraglide.js library to prevent telemetry data from being sent during CI runs. This avoids potential issues with telemetry interfering with the build process and causing timeouts.
- Configures Deno to use a local cache to speed up installations and ensure reproducibility.

fix / disable paraglide.js telemetry in CI

---

projects/client/src/routes/auth/device/+page.svelte

fix(auth): vertically center qr code container

---

projects/client/src/routes/+layout.svelte

- Also sets the background color in the html element
- Set in a pseudo element so it will always be below background images
Example with body hidden, in dark mode.
Before:
After:

fix: also set the background color on the html

---

projects/client/src/lib/features/auth/stores/useUser.ts
projects/client/src/lib/features/auth/token/index.ts
projects/client/src/lib/requests/_internal/createAuthenticatedFetch.ts

- Enables routing requests from users with "director" status to the HD instance of the up-next nitro endpoint.
- This allows internal testing of the HD nitro feature.

feat(up-next): route director requests to hd instance

---

projects/client/src/lib/requests/_internal/mapToMediaVideo.ts
projects/client/src/lib/requests/models/MediaVideo.ts
projects/client/src/lib/requests/queries/movies/movieVideosQuery.spec.ts
projects/client/src/lib/requests/queries/movies/movieVideosQuery.ts
projects/client/src/lib/requests/queries/movies/showVideosQuery.spec.ts
projects/client/src/lib/requests/queries/movies/showVideosQuery.ts
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticVideoMappedMock.ts
projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloVideoMappedMock.ts

This pull request introduces changes to include a `publishedAt` field for media videos, ensuring proper handling of publication dates across the application. The changes also add sorting functionality to organize videos by their publication date in ascending order.
* [`projects/client/src/lib/requests/models/MediaVideo.ts`](diffhunk://#diff-611fe6545b7777cace9df7b71460788e0e90e2fb54a11aae3a2d0a382420149fR19): Added a new `publishedAt` field to the `MediaVideoSchema` with a `z.date()` type to validate media video publication dates.
* [`projects/client/src/lib/requests/_internal/mapToMediaVideo.ts`](diffhunk://#diff-0df72f0e06a7b20291e4a11ae2996477a3e137eeb29af40f60f64ac7edcaba50R20): Updated the `mapToMediaVideo` function to include the `publishedAt` field when mapping video data.
* …

feat(summary): ensure videos are in publish order

---

projects/client/src/app.html
projects/client/src/lib/sections/navbar/Navbar.svelte
projects/client/src/lib/utils/devices/isPWA.ts
projects/client/src/routes/+layout.svelte
projects/client/src/routes/_design_system/pwa/+layout.svelte
projects/client/src/routes/_design_system/pwa/android/+page.svelte
projects/client/src/routes/_design_system/pwa/ios/+page.svelte
projects/client/src/style/scss/mixins/index.scss

Adds a PWA simulator for testing and development, enhancing the design system.
Key changes:
- Introduces routes for simulating PWA behavior on Android and iOS.
- Define simulator for Android.
- Enhances PWA detection logic to include simulator flag.
- Improves Content Security Policy to allow simulator scripts.
- Applies PWA styling using a class on the body element.
Test here: http://localhost:5173/_design_system/pwa/android
https://github.com/user-attachments/assets/2fd752e0-5801-43de-8734-d057691f861a

feat: define pwa simulator for android

---

projects/client/src/lib/features/auth/stores/useUser.ts
projects/client/src/lib/requests/_internal/createAuthenticatedFetch.ts

- Removes the `isDirector` check for accessing HD up-next data, making it available to all users.
- Cleans up associated code related to internal testing.

Enables HD up-next data for all users

---

projects/client/src/lib/components/summary/SummaryPoster.svelte
projects/client/src/lib/sections/summary/components/overlay/StreamOnOverlay.svelte
projects/client/src/style/theme/global.css

- The overlay needs a static color.
Before:
After:

fix(summary): poster overlay colors in light mode

---

projects/client/src/lib/components/card/CardCover.svelte
projects/client/src/lib/components/card/CardCoverProps.ts
projects/client/src/lib/features/image/components/CrossOriginImage.svelte
projects/client/src/lib/features/image/components/ImageProps.ts
projects/client/src/lib/sections/lists/components/MediaCard.svelte
projects/client/src/style/theme/modes.scss

Improves the visual appeal of media cards by displaying logos over the cover images.
- Adds an `overlaySrc` property to the `CardCover` component, allowing a logo to be displayed on top of the cover image.
- Implements styling to ensure the logo is appropriately positioned and visually appealing.
- Introduces fallback to title text if a logo is unavailable.

feat / enhances card covers with logo overlays

---

deno.lock
projects/client/package.json
projects/client/src/lib/components/card/CardCover.svelte
projects/client/src/lib/components/icons/WatchlistIcon.svelte
projects/client/src/lib/requests/queries/lists/listItemsQuery.ts
projects/client/src/lib/requests/queries/movies/movieAnticipatedQuery.ts
projects/client/src/lib/requests/queries/movies/movieFavoritesQuery.ts
projects/client/src/lib/requests/queries/movies/movieListsQuery.ts
projects/client/src/lib/requests/queries/movies/moviePopularQuery.ts
projects/client/src/lib/requests/queries/movies/movieRelatedQuery.ts
projects/client/src/lib/requests/queries/movies/movieStreamingQuery.ts
projects/client/src/lib/requests/queries/movies/movieTrendingQuery.ts
projects/client/src/lib/requests/queries/recommendations/recommendedMoviesQuery.ts
projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
projects/client/src/lib/requests/queries/shows/showAnticipatedQuery.ts
projects/client/src/lib/requests/queries/shows/showFavoritesQuery.ts
projects/client/src/lib/requests/queries/shows/showPopularQuery.ts
projects/client/src/lib/requests/queries/shows/showRelatedQuery.ts
projects/client/src/lib/requests/queries/shows/showStreamingQuery.ts
projects/client/src/lib/requests/queries/shows/showTrendingQuery.ts
projects/client/src/lib/requests/queries/users/movieWatchlistQuery.ts
projects/client/src/lib/requests/queries/users/personalListsQuery.ts
projects/client/src/lib/requests/queries/users/showWatchlistQuery.ts
projects/client/src/lib/requests/queries/users/userListItemsQuery.ts
projects/client/src/lib/sections/lists/components/MediaCard.svelte

- Updates several queries to include `colors` in the extended data.
- Modifies card cover to use the secondary color from the fetched media palette as the cover shadow, enhancing visual appeal.
- Removes unused CSS rules for watchlist icon states, simplifying the component's styling.

feat / data fetching with color palette

---

projects/client/vite.config.ts

- Deployments were broken after the package updates.
- The cloudflare files were not generated.
- Strange that the adapter is ignored depending on the plugin order 🤔
Files are generated now:

chore: change config to generate cloudflare files

---

projects/client/src/lib/requests/queries/movies/movieFavoritesQuery.spec.ts
projects/client/src/lib/requests/queries/movies/movieFavoritesQuery.ts
projects/client/src/lib/requests/queries/shows/showFavoritesQuery.spec.ts
projects/client/src/lib/requests/queries/shows/showFavoritesQuery.ts
projects/client/src/lib/sections/lists/FavoritesList.svelte
projects/client/src/lib/sections/lists/stores/useFavoritesList.ts
projects/client/src/lib/sections/profile/Profile.svelte

- Fixes the issue where all profile pages showed the current users favorites 😅
Before:
After:

fix(profile): show correct favorites on profile pages

---

projects/client/src/lib/utils/media/toMediaIntl.ts
projects/client/src/routes/movies/[slug]/useMovie.ts
projects/client/src/routes/shows/[slug]/seasons/[season]/episodes/[episode]/useEpisode.ts
projects/client/src/routes/shows/[slug]/useShow.ts

Ensures a smoother user experience by displaying default data when internationalized content is unavailable.
- Modifies the `toMediaIntl` function to utilize fallback data (typically the original entry) if the internationalized data is missing.
- Updates relevant components to provide the original data as the fallback.
Fixes: #764

fix: use english media information as fallback when intl is missing

---

projects/client/src/lib/sections/footer/Footer.svelte
projects/client/src/lib/sections/footer/constants.ts
projects/client/src/lib/sections/now-playing/_internal/NowPlayingToast.svelte
projects/client/src/lib/sections/now-playing/_internal/useFooterHeight.ts
projects/client/src/style/layout/index.css

- On mobile layout, on your own profile page, the footer was cut off.
- This was because the content could be dynamic, but the height was static.
- The footer size can now also be dynamic; the now playing toast checks the actual element for its size.
Before:
https://github.com/user-attachments/assets/dad47419-3a79-4ca2-82bc-6f6e0260c302
After:
https://github.com/user-attachments/assets/7a299e4e-911d-4302-8e0f-9afd40391ee0

fix(footer): allow dynamic footer sizing

---

projects/client/src/lib/sections/lists/components/EpisodeItem.svelte

- Add render guard for the episode action.
Before:
After:

fix(episode): do not show mark as watched for unauthenticated users

---

projects/client/src/lib/features/navigation/navigationTrap.ts
projects/client/src/lib/sections/navbar/components/filter/filters/_internal/SelectFilter.svelte

- Do not use nav trap when not using d-pad.
Before/after:
https://github.com/user-attachments/assets/2d4b677d-5dcb-4429-840a-6309743d16f8
https://github.com/user-attachments/assets/94b23323-adbb-4ef9-87b6-142f0766c58d

fix(filter): only enable navigation trap for d-pad

---

projects/client/src/lib/sections/summary/components/details/_internal/CollapsableValues.svelte

- Fixes ellipsis for links in the details grid on summary pages
Before/after:
Before/after:

fix(summary): ellipse content in details grid

---

projects/client/src/lib/components/gestures/SwipeX.svelte

- After lazy loading elements with a gesture container, the width could become larger than the column.
Before:
https://github.com/user-attachments/assets/cdbf84dc-58ea-430a-9524-e1ea1c50873d
After:
https://github.com/user-attachments/assets/ac33c135-4590-48cc-9a7d-0d53caec0099

fix(gestures): keep consistent size when lazy loading gesture container

---

projects/client/src/lib/stores/_internal/findPreferredStreamingService.spec.ts
projects/client/src/lib/stores/_internal/findPreferredStreamingService.ts

- Fixes the services match priority to be:
- Match one of your favorites.
- If no hit, pick the first available streaming service, based on the sorted list.
- If no hit, fall back to plex.

fix(streaming): prioritize services over plex

---

projects/client/src/lib/components/media/streaming-service/StreamingServiceLogo.svelte

- Fall back to displaying service name if there is no logo.
Hardcoded example:
When there is an image:
When there is no image:

fix(streaming): fall back to service name when there is no image

---

projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/components/episode/tags/ShowProgressTag.svelte
projects/client/src/lib/sections/lists/components/EpisodeItem.svelte
projects/client/src/style/theme/global.css

- The amount of blurred backgrounds were causing some performance issues; especially on the home page, since all these items have blurs:
- Changes:
- For the tags, the blur is removed, and the background color is made less transparent.
- For the action buttons in the card footers, the blur is removed.
- These changes were discussed with @anodpixels 
- Until we can find a better way of dealing with blurs, we should refrain from using blur on components that repeat so often on a page.
- Still strange that it's so computationally heavy, might be worth it to investigate this more later on. For now this is a good enough alternative I'd say.
I hope the screen recording captures it well enough. When scrolling you can see how choppy/smooth the navbar transitions.
Before: …

perf: less blurring for increased performance

---

projects/client/src/routes/shows/[slug]/+page.svelte

- Could have a race condition when going to a show summary. This now waits for the season number to be there.

fix(summary): waits for valid season number before opening summary

---

projects/client/src/lib/components/buttons/ActionButton.svelte

- Action buttons used `ni-6`; which didn't exist. But which I added in an earlier commit. Causing action buttons suddenly to be bigger.
Before:
After:

fix(button): accounts for the now existing padding

---

projects/client/src/lib/components/buttons/share/ShareButton.svelte
projects/client/src/lib/sections/profile-banner/ProfilePageBanner.svelte

- Own profiles were shared with the `/me` link. This fix uses the actual slug when sharing your own profile.

fix(profile): uses actual slug when sharing own profile

---

projects/client/src/lib/components/card/CardActionBar.svelte

- Action bar no longer blocks clicks on the card.
Before:
https://github.com/user-attachments/assets/34b0648a-1580-41fe-8c3c-62076590cdfb
After:
https://github.com/user-attachments/assets/a6142ee0-f9b4-4ad3-b7d7-9f2801271f63

fix(card): makes action bar ignore pointer events

---

projects/client/src/lib/components/lists/grid-list/GridList.svelte
projects/client/src/lib/components/lists/section-list/ShadowList.svelte

- Uses the list length also as part of the key; scroll positions are no longer maintained on list length changes.
- Could probably be improved by using a hash based on the exact content 🤔 
Before:
https://github.com/user-attachments/assets/98beb0e7-50e1-48c6-a23c-f800d8c7ee0b
After:
https://github.com/user-attachments/assets/1118d5fa-6c49-4139-9db2-12399f750b6a

fix(list): do not persist scroll position on list length change

---

projects/client/src/lib/sections/summary/components/comments/_internal/ShadowScroller.svelte

- Comment shadows no longer cross list shadows.
Before:
https://github.com/user-attachments/assets/00e5d028-f0e6-4ad4-a159-8da902f60e1d
After:
https://github.com/user-attachments/assets/dbf80618-e558-4869-8965-e10d9c2ad39a

fix(comment): places comment shadow below list shadow

---

projects/client/src/lib/features/auth/components/AuthProvider.svelte
projects/client/src/lib/features/auth/getOidcConfig.ts
projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
projects/client/src/lib/features/auth/stores/initializeUserManager.ts
projects/client/src/routes/+layout.server.ts
projects/client/src/routes/api/store-token/+server.ts
projects/client/src/routes/silent-redirect/+page.svelte
projects/client/test/mocks/oidc-client-ts.mock.ts

- Pt. 1 of some OIDC fixes (flows tested on staging with shorter token expiry):
- While using Lite, tokens will be refreshed one minute before expiry.
- When opening Lite after a token was already expired, it will now be refreshed properly.
- The refresh triggered by the initialization will block rendering until refreshed.
- Small fix to the user settings that broke testing on non official apps.
- Non official apps only return a uuid instead of the trakt id when requesting user settings.

fix(auth): refresh oidc tokens

---

projects/client/src/lib/features/auth/stores/initializeUserManager.ts

- The refresh in `signinSilent` does not trigger `addSilentRenewError` apparently

fix(auth): handles failed silent sign-ins

---

projects/client/src/lib/features/navigation/_internal/dpadController.ts

- Fixes the case where when using the d-pad, selecting a season would jump to the top of the page.
Before:
https://github.com/user-attachments/assets/c7a091f8-15b1-45f6-b1e3-76145f1bbf38
After:
https://github.com/user-attachments/assets/6a8a8137-c431-4022-a6c3-2c56cae09cd2

fix(navigation): do not reset focus when staying on the same route

---

projects/client/i18n/meta/bg-bg.json
projects/client/i18n/meta/da-dk.json
projects/client/i18n/meta/de-de.json
projects/client/i18n/meta/en.json
projects/client/i18n/meta/es-es.json
projects/client/i18n/meta/es-mx.json
projects/client/i18n/meta/fr-ca.json
projects/client/i18n/meta/fr-fr.json
projects/client/i18n/meta/it-it.json
projects/client/i18n/meta/ja-jp.json
projects/client/i18n/meta/nb-no.json
projects/client/i18n/meta/nl-nl.json
projects/client/i18n/meta/pl-pl.json
projects/client/i18n/meta/pt-br.json
projects/client/i18n/meta/ro-ro.json
projects/client/i18n/meta/sv-se.json
projects/client/i18n/meta/uk-ua.json
projects/client/src/lib/sections/lists/user/PersonalLists.svelte
projects/client/src/lib/sections/lists/user/_internal/CreateListAction.svelte
projects/client/src/lib/sections/lists/user/_internal/CreateListButton.svelte
projects/client/src/lib/sections/lists/user/_internal/CreateListHeader.svelte
projects/client/src/lib/sections/lists/user/_internal/useCreateList.ts

- Prefers `create` over `add` when creating new lists.
- The button now display `List +` instead of `Add list +`.
Before:
After:

refactor(list): use consistent naming for creating new lists

---

projects/client/i18n/meta/bg-bg.json
projects/client/i18n/meta/da-dk.json
projects/client/i18n/meta/de-de.json
projects/client/i18n/meta/en.json
projects/client/i18n/meta/es-es.json
projects/client/i18n/meta/es-mx.json
projects/client/i18n/meta/fr-ca.json
projects/client/i18n/meta/fr-fr.json
projects/client/i18n/meta/it-it.json
projects/client/i18n/meta/ja-jp.json
projects/client/i18n/meta/nb-no.json
projects/client/i18n/meta/nl-nl.json
projects/client/i18n/meta/pl-pl.json
projects/client/i18n/meta/pt-br.json
projects/client/i18n/meta/ro-ro.json
projects/client/i18n/meta/sv-se.json
projects/client/i18n/meta/uk-ua.json
projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
projects/client/src/lib/features/auth/stores/useUser.ts
projects/client/src/lib/sections/settings/Settings.svelte
projects/client/src/lib/sections/settings/_internal/Profile.svelte
projects/client/src/lib/sections/settings/_internal/SettingsBlock.svelte
projects/client/src/lib/sections/settings/_internal/constants.ts
projects/client/src/lib/sections/settings/_internal/getSwitchInnerText.ts
projects/client/src/lib/sections/settings/_internal/useSettings.ts
projects/client/src/mocks/data/users/mapped/ExtendedUserSettingsMappedMock.ts

- Adds initial profile settings.
- More to follow (like name/about me/etc).

feat(settings): adds minor profile settings

---

projects/client/i18n/meta/en-au.json

Adjusted enAU translation guidance to stick with the original English translations except for certain AU-specific spelling to avoid confusion.

Adjusted enAU translations guidance

---

projects/client/i18n/meta/bg-bg.json
projects/client/i18n/meta/da-dk.json
projects/client/i18n/meta/de-de.json
projects/client/i18n/meta/en-au.json
projects/client/i18n/meta/en.json
projects/client/i18n/meta/es-es.json
projects/client/i18n/meta/es-mx.json
projects/client/i18n/meta/fr-ca.json
projects/client/i18n/meta/fr-fr.json
projects/client/i18n/meta/it-it.json
projects/client/i18n/meta/ja-jp.json
projects/client/i18n/meta/nb-no.json
projects/client/i18n/meta/nl-nl.json
projects/client/i18n/meta/pl-pl.json
projects/client/i18n/meta/pt-br.json
projects/client/i18n/meta/ro-ro.json
projects/client/i18n/meta/sv-se.json
projects/client/i18n/meta/uk-ua.json

Refines several i18n labels across multiple languages:
- Shortens "Most Anticipated" and "Most Popular" to "Anticipated" and "Popular" respectively, improving conciseness.
- Replaces "Streaming" with "Availability" or similar phrases in different languages, enhancing user understanding of the feature.

Refactors i18n labels for clarity

---

projects/client/i18n/meta/en-au.json

Fixed translations that slipped through before enAU guidance change in #885

Fixed enAU translations prior to guidance change

---

projects/client/i18n/meta/en.json
projects/client/src/lib/components/lists/_internal/ListHeader.svelte
projects/client/src/lib/sections/lists/watchlist/ReleasedList.svelte
projects/client/src/lib/sections/lists/watchlist/UnreleasedList.svelte
projects/client/src/lib/sections/lists/watchlist/WatchList.svelte
projects/client/src/lib/sections/lists/watchlist/WatchlistPaginatedList.svelte
projects/client/src/lib/sections/lists/watchlist/_internal/WatchlistTag.svelte
projects/client/src/routes/users/[user]/lists/+page.svelte

- All watchlist based lists are now tagged. For the released/unreleased ones, only a read-only tag for informational purposes.

feat(list): adds tags to other watchlist based lists

---

projects/client/src/lib/components/card/CardFooter.svelte
projects/client/src/lib/components/media/tags/DurationTag.svelte
projects/client/src/lib/sections/lists/components/DefaultMediaItem.svelte

- Adds year chip to movie card footers.

feat(footer): add year chip to all movies

---

projects/client/src/lib/components/background/CoverImage.svelte
projects/client/src/routes/search/+page.svelte

- Uses more clear cover images on small devices
Before/after:
Before/after:

fix(cover): use more clear cover images on small devices

---

projects/client/src/lib/components/media/tags/AirDateTag.spec.ts
projects/client/src/lib/components/media/tags/AirDateTag.svelte
projects/client/src/lib/sections/lists/components/DefaultMediaItem.svelte
projects/client/src/lib/sections/lists/components/EpisodeItem.svelte
projects/client/src/lib/sections/summary/components/details/_internal/useMediaDetails.ts
projects/client/src/lib/sections/summary/components/media/MediaMetaInfo.svelte
projects/client/src/lib/utils/date/isMaxDate.ts

Refactors the AirDate tag to rely solely on the `airDate` property and introduces a utility function to determine if a date represents an unknown or TBA state. This removes the need for a separate `year` property and centralizes the logic for displaying "TBA" status.
- Uses `isMaxDate` to check if the airDate represents a "To Be Announced" state.
- Simplifies components using the AirDate tag by removing the year prop.

fix(summary): display TBA for unknown dates

---

projects/client/src/lib/sections/landing/Landing.svelte
projects/client/src/lib/sections/landing/components/Step.svelte
projects/client/src/lib/sections/landing/components/Steps.svelte

fix(landing): responsiveness on smaller screens

---

projects/client/src/lib/features/search/SearchProvider.svelte

- Search mode toggle now also works when the search query is empty.

fix(search): allow search mode toggle when there is no search term

---

.github/CODEOWNERS

- Added a codeowners file & change the branch rules to require an approval by an owner.
- ~~Removing the auto gemini pr-review for now.~~ Even though it's instructed to `Don't Approve The Pull Request`, it beautifully ignores it: `I see no issues, so I'll approve the PR with a brief summary comment`.
Enabled rule:

ci: remove gemini auto review

---

projects/client/src/lib/components/background/CoverImage.svelte
projects/client/src/lib/features/search/SearchInput.svelte
projects/client/src/lib/sections/navbar/MobileNavbar.svelte
projects/client/src/lib/sections/navbar/components/TopNavbar.svelte
projects/client/src/style/theme/modes.scss

- pt1 of the mobile navbar design changes.
- Focuses on mostly low hanging fruit.
- Will need to be followed up with:
- Move the search to the bottom navbar.
- Auto hide/unhide behavior for the top navbar.
Before:
https://github.com/user-attachments/assets/a3745908-9844-454e-8bcc-4e89c0ace3e2
After:
https://github.com/user-attachments/assets/fe015076-2afe-4362-9441-982d0f242582
Simulator test for the safe area insets:
https://github.com/user-attachments/assets/9a6cfd00-00f6-4bcb-b320-84a337b71956

feat(navbar): new design

---

projects/client/src/app.d.ts
projects/client/src/lib/requests/_internal/createAuthenticatedFetch.ts
projects/client/src/lib/requests/_internal/mediumUrl.ts
projects/client/src/lib/requests/_internal/thumbUrl.ts
projects/client/vite.config.ts

- Ensures API requests are routed to the "hd." subdomain instead of "apiz." 
- Adds a build-time constant for the HD target to avoid hardcoding
- Skips replacement for requests including "watchnow"

Routes API requests to HD domain

---

projects/client/src/lib/requests/_internal/mapToHeadshot.ts
projects/client/src/lib/requests/_internal/mapToMediaCrew.ts
projects/client/src/lib/requests/_internal/mapToPersonSummary.ts
projects/client/src/lib/requests/models/MediaCrew.ts
projects/client/src/lib/requests/models/PersonSummary.ts
projects/client/src/lib/sections/lists/PersonList.svelte
projects/client/src/lib/sections/lists/components/CastMemberItem.svelte
projects/client/src/lib/sections/summary/PeopleSummary.svelte
projects/client/src/mocks/data/people/mapped/PersonFergusonMappedMock.ts
projects/client/src/mocks/data/summary/episodes/silo/mapped/EpisodeSiloPeopleMappedMock.ts
projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticPeopleMappedMock.ts
projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloPeopleMappedMock.ts
projects/client/src/routes/people/[slug]/+page.svelte
projects/client/src/routes/search/+page.svelte

- Headshot images were always used as is 😅 This fixes it to map to `medium` and `thumb` versions and uses the correct one where applicable.

fix: use medium and thumb images for headshots

---

projects/client/i18n/meta/bg-bg.json
projects/client/i18n/meta/da-dk.json
projects/client/i18n/meta/de-de.json
projects/client/i18n/meta/en-au.json
projects/client/i18n/meta/en.json
projects/client/i18n/meta/es-es.json
projects/client/i18n/meta/es-mx.json
projects/client/i18n/meta/fr-ca.json
projects/client/i18n/meta/fr-fr.json
projects/client/i18n/meta/it-it.json
projects/client/i18n/meta/ja-jp.json
projects/client/i18n/meta/nb-no.json
projects/client/i18n/meta/nl-nl.json
projects/client/i18n/meta/pl-pl.json
projects/client/i18n/meta/pt-br.json
projects/client/i18n/meta/ro-ro.json
projects/client/i18n/meta/sv-se.json
projects/client/i18n/meta/uk-ua.json
projects/client/src/lib/sections/footer/Footer.svelte
projects/client/src/lib/sections/landing/Landing.svelte
projects/client/src/lib/sections/landing/components/Step.svelte
projects/client/src/lib/sections/landing/components/Steps.svelte

Refreshes the landing page copy to be more concise and impactful.
Also, adjusts translations to reflect the updated copy and improve overall clarity and consistency across languages.

feat(landing): page copy and translations

---

projects/client/src/lib/sections/now-playing/_internal/useScrollDistance.ts

- Correctly sets initial position of the now playing toast.
Before:
https://github.com/user-attachments/assets/625684b4-652a-4fdf-84c7-14c1ed7befb9
After:
https://github.com/user-attachments/assets/20e907d4-962d-447b-8c06-0af8f24b5135

fix(checkin): correctly set initial position of now playing toast

---

projects/client/src/lib/sections/lists/watchlist/useUnreleasedList.ts

- Fixes https://github.com/trakt/trakt-web/issues/954
- Also fixes a small bug to filter out 'garbage' (e.g. old released movies that don't have a known air date).
- I left a fixme in there to handle this better on an API level. It might be better to even switch to the calendar API for these 🤔 
Before:
After:

fix(upcoming): sort upcoming movies

---

projects/client/vite.config.ts

- Adds source maps to builds.
Examples from a preview build:

chore: enable source maps

---

projects/client/src/lib/features/auth/stores/useUser.ts
projects/client/src/lib/sections/lists/season/_internal/SeasonEpisodeList.svelte
projects/client/src/lib/sections/summary/components/stream/_internal/usePlexCollection.ts

- Error provider is already paying off.
- Only assume user settings data is defined since that's the only one that's prefetched.
Before:
https://github.com/user-attachments/assets/c2910894-a496-4a19-a020-17212cc2adef
After:
https://github.com/user-attachments/assets/1dec51b9-41ee-474f-82a4-172cfbe5e501

fix(user): only assume defined data for prefetched query

---

projects/client/src/lib/sections/lists/components/EpisodeItem.svelte

- Use show runtime if ep runtime is not known.
- ~~The 0 remaining also seems weird, since we do know the episode count. I'll check on hyperdrive.~~ nvm, is a client side check, number is correct since it checks aired vs completed.
Before:
After:

fix(summary): deal with unknown episode runtime on show summary

---

projects/client/i18n/generator/core/I18nGenerator.spec.ts
projects/client/i18n/generator/utils/generateAndroidResourceFolder.spec.ts
projects/client/i18n/generator/utils/generateAndroidResourceFolder.ts

Forces the use of the 'values' resource folder for the English
locale, regardless of regional variations. This simplifies
resource management for the default language.

fix(i18n): ensures 'values' is used for en locale

---

projects/client/src/lib/components/toggles/ToggleOption.ts
projects/client/src/lib/components/toggles/Toggler.svelte
projects/client/src/lib/sections/lists/activity/ActivityList.svelte
projects/client/src/lib/sections/lists/activity/_internal/ActivityToggle.svelte
projects/client/src/lib/sections/lists/watchlist/WatchList.svelte
projects/client/src/lib/sections/lists/watchlist/WatchlistPaginatedList.svelte
projects/client/src/lib/sections/lists/watchlist/_internal/TypeToggles.svelte

Refactors the toggle components to be more generic and reusable.
- Introduces a new `Toggler` component that handles both combo and radio button toggle types.
- Creates a `ToggleOption` interface to define the structure of toggle options.
- Replaces the specific toggle implementations in the activity list and watchlist with the new `Toggler` component.

refactor: extract common toggler component

---

projects/client/i18n/generator/utils/escapeXml.ts
projects/client/i18n/meta/en.json

- enable required strings already present
- add some new ones to fill the gaps
- use ellipsis symbol instead of 3 dots

feat(i18n): sync Android strings with EN source

---

projects/client/src/routes/users/[user]/lists/[list]/+page.svelte

- Do not rerender list items after renaming.
- The list items were being rerendered since it depended on the loading state of the list summary 🤦
Before:
https://github.com/user-attachments/assets/2e99091b-91a5-4c9a-a846-0b0b0bb1c50f
After:
https://github.com/user-attachments/assets/45e9186b-0cc9-40a1-86e6-713be9a546f4

fix(list): do not rerender list items  after rename

---

projects/client/src/lib/utils/actions/mobileAppleDeviceTriggerHack.ts

- This navigation check hasn't worked in a while, it's been throwing lifecyle errors. Reverting it since the original issue it was supposed to fix no longer is applicable: https://github.com/trakt/trakt-web/issues/291
- If we ever do cards in a popup like that again, we can use usePortal nowadays adds an underlay; which adds an underlay you can't click through.
- I did play around a bit with beforeNavigate and afterNavigate outside of the handler; they're never called before the requestAnimationFrame.

fix: do not use navigation outside component initialisation

---

projects/client/src/lib/components/dropdown/DropdownList.svelte

- Open dropdown at correct location
Before:
https://github.com/user-attachments/assets/a6ae5e29-aa06-4098-a5fa-0d8553e5087e
After:
https://github.com/user-attachments/assets/f6638a6f-f5bd-40dd-ab87-c62daaee6e14
Before:
https://github.com/user-attachments/assets/970006a5-538f-4ab1-a935-a7722bf62d29
After:
https://github.com/user-attachments/assets/fd311cd4-4159-4318-94f6-1d54650dbbf6

fix(dropdown): open at correct location

---

.github/actions/setup-deno/action.yml
deno.json

- Forgot to revert the fixed deno version 🥲 This should fix the builds:
- Sets the `nodeModulesDir` to `manual` to fix:
Recommended here: https://github.com/denoland/deno/issues/30424#issuecomment-3200006441
The docs also mention: [`It is recommended for projects using frameworks like Next.js, Remix, Svelte, Qwik etc, or tools like Vite, Parcel or Rollup.`](https://docs.deno.com/runtime/fundamentals/node/#automatic-node_modules-creation)

Reverts to using version range for Deno version

---

projects/client/src/lib/sections/footer/Footer.svelte

- Reserve space for the now playing toast in the footer
Before:
After:

fix(footer): reserve space for now playing toast

---

projects/client/src/lib/components/toggles/Toggler.svelte

- Content could be changed while the toggler is still animating, leading to sluggish animations. The onchange will now be called on transition end.
Before:
https://github.com/user-attachments/assets/01b04687-837f-497b-80d1-84cb9a308de7
After:
https://github.com/user-attachments/assets/b8c42a34-0a0f-4ef1-bb1e-4309834cde13

fix(toggle): change after transition

---

projects/client/src/lib/utils/formatting/date/toHumanETA.spec.ts
projects/client/src/lib/utils/formatting/date/toHumanETA.ts
projects/client/vitest-setup.ts

Improves the accuracy of the estimated time of arrival (ETA) calculation by:
- Using `round` instead of `ceil` for time differences to avoid overestimation.
- Showing minutes for ETAs less than an hour, providing more granular information.
- Corrects logic for same-day ETAs, especially around midnight.
The changes ensure more accurate and user-friendly ETA displays.
Before:
After:

Refines ETA calculation for improved accuracy

---

projects/client/src/lib/sections/lists/components/SeasonItem.svelte

- When opening a show summary, scroll to the current season if it is not in view.
Before:
https://github.com/user-attachments/assets/29fa0188-2f74-435c-962f-3f6ad85c33fb
After:
https://github.com/user-attachments/assets/46d6ee0b-9ad4-43df-9d1c-2b7d6ae2c2d0

fix(summary): scroll current season into view

---

projects/client/src/lib/features/calendar/Calendar.svelte
projects/client/src/lib/sections/navbar/components/TopNavbar.svelte
projects/client/src/lib/utils/actions/trackWindowScrollDirection.ts

- Added an offset before hiding the top navbar.
- It hides only after we can reliably fill up the space under it to avoid having gaps.
- Calendar responds accordingly now.
Before/after:
https://github.com/user-attachments/assets/0d9cff14-778a-4569-923b-5c5ffe809fc0
https://github.com/user-attachments/assets/185c3eac-b04f-4b02-a206-95c286a83605
Before/after:
https://github.com/user-attachments/assets/46ccfbc7-4130-4660-8ffc-ab01cb3caf48
https://github.com/user-attachments/assets/a46ec6ed-9fc8-4bba-bd12-dd6ba419afa3

Fix/calendar & navbar scroll behavior

---

projects/client/src/app.html
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/ReactionDetails.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/ReactionEmoji.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/ReactionPicker.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/ReactionsDistribution.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/ReactionsSummary.svelte
projects/client/src/lib/sections/summary/components/comments/_internal/comment-actions/constants.ts

- Adds animated emojis to reactions.
- ~~Current selection is continuously animated.~~
- ~~In all other cases, they are animated for 1.5sec on mount.~~
- In the distribution, the current reaction is animated infinitely.
- In the picker, they are animated for a short duration as the appear.
New:
https://github.com/user-attachments/assets/ca23cae3-9bc8-4482-b2c8-7ae7e99fcf73
Old:
https://github.com/user-attachments/assets/2d2f7838-8fec-4629-8014-274f3d4c9c5c

feat(comment): use animated emojis

---

projects/client/src/routes/shows/[slug]/+page.svelte

This commit will improve the logic for selecting the active season in the show details page.
It addresses an issue where the active season wasn't correctly identified. The changes ensure that the season is correctly identified by comparing both episode counts and the season number when determining if the current season is fully watched. Additionally, it ensures that a season is always selected, even if the user hasn't watched any episodes.

fix(show): improve season selection logic

---

projects/client/src/lib/pages/errors/ErrorLockedAccountPage.svelte

- Fix for [error page using context that is not available](https://trakt-tv.sentry.io/issues/59227721/?query=is%3Aunresolved&referrer=issue-stream&sort=freq).

fix(errors): do not depend on contexts in error pages

---

projects/client/i18n/meta/bg-bg.json
projects/client/i18n/meta/da-dk.json
projects/client/i18n/meta/de-de.json
projects/client/i18n/meta/en-au.json
projects/client/i18n/meta/en.json
projects/client/i18n/meta/es-es.json
projects/client/i18n/meta/es-mx.json
projects/client/i18n/meta/fr-ca.json
projects/client/i18n/meta/fr-fr.json
projects/client/i18n/meta/it-it.json
projects/client/i18n/meta/ja-jp.json
projects/client/i18n/meta/nb-no.json
projects/client/i18n/meta/nl-nl.json
projects/client/i18n/meta/pl-pl.json
projects/client/i18n/meta/pt-br.json
projects/client/i18n/meta/ro-ro.json
projects/client/i18n/meta/sv-se.json
projects/client/i18n/meta/uk-ua.json
projects/client/src/lib/features/search/SearchPlaceHolder.svelte

- Uses the same list title for all search types when there is no search query.
- Had a quick chat with Coco, we're going with `Most Popular Searches`. cc @michaldrabik

fix(search): use same label for all popular search types

---

projects/client/src/lib/sections/summary/components/media/v2/MediaSummary.svelte
projects/client/src/lib/sections/summary/components/media/v2/_internal/SpoilerSection.svelte

- Adds spoiler section for media overview.
- @anodpixels is still to do a pass over the design/interaction.
- i18n will be tackled when finalizing design.
https://github.com/user-attachments/assets/b0b97180-040e-4b6a-8f84-7024435e0e31

feat(summary): add spoiler section for summary v2

---

projects/client/src/lib/features/analytics/events/AnalyticsEvent.ts
projects/client/src/lib/features/analytics/events/AnalyticsEventDataMap.ts
projects/client/src/lib/features/search/SearchResultsGrid.svelte
projects/client/src/lib/sections/landing/components/TrendingItems.svelte
projects/client/src/lib/sections/lists/CreditsList.svelte
projects/client/src/lib/sections/lists/FavoritesList.svelte
projects/client/src/lib/sections/lists/RelatedList.svelte
projects/client/src/lib/sections/lists/anticipated/AnticipatedListItem.svelte
projects/client/src/lib/sections/lists/components/DefaultPersonItem.svelte
projects/client/src/lib/sections/lists/components/MediaCard.svelte
projects/client/src/lib/sections/lists/components/MediaCardProps.ts
projects/client/src/lib/sections/lists/components/MediaSummaryCard.svelte
projects/client/src/lib/sections/lists/popular/PopularListItem.svelte
projects/client/src/lib/sections/lists/recommended/RecommendedListItem.svelte
projects/client/src/lib/sections/lists/trending/TrendingListItem.svelte
projects/client/src/lib/sections/lists/watchlist/WatchlistItem.svelte

- Summary drilldown telemetry for media & person cards
- To follow: episode/activity items

chore(analytics): also add telemetry for summary drilldowns

---

projects/client/src/lib/requests/_internal/createAuthenticatedFetch.ts

Removes the logic that replaced the URL in the request to the Trakt API.
We'll delegate this to the server.

refactor: remove unnecessary url replacement

---

projects/client/src/lib/sections/summary/components/episode/v2/EpisodeSummary.svelte
projects/client/src/lib/sections/summary/components/media/v2/MediaSummary.svelte

- Only pass in the summary poster tags if there should be any so it can transition in.
https://github.com/user-attachments/assets/acef87c3-10ac-4c45-9d86-1e1afbfece5c

fix(summary): fade in poster tags

---

projects/client/src/lib/sections/summary/components/episode/v2/EpisodeSummary.svelte
projects/client/src/lib/sections/summary/components/media/v2/MediaSummary.svelte

- No links on mobile summary posters.

fix(summary): disable poster links on mobile version

---

projects/client/src/lib/components/episode/tags/ShowProgressTag.svelte
projects/client/src/lib/components/media/tags/ActivityTag.svelte
projects/client/src/lib/components/media/tags/AirDateTag.svelte
projects/client/src/lib/components/media/tags/DurationTag.svelte
projects/client/src/lib/components/media/tags/EpisodeCountTag.svelte
projects/client/src/lib/sections/lists/components/DefaultMediaItem.svelte
projects/client/src/lib/sections/lists/components/EpisodeItem.svelte
projects/client/src/lib/sections/lists/components/MediaSummaryCard.svelte

- Updates the tags in summary cards to match new design.
- This is pt1., pt2 will be the activity summary cards.
Before/after:
Before/after:
Before/after:

feat(card): use text only tags in media and episode summary cards

---

projects/client/src/lib/components/media/tags/MediaTypeTag.svelte
projects/client/src/lib/components/media/tags/TagIntl.ts
projects/client/src/lib/components/media/tags/TagIntlProvider.ts
projects/client/src/lib/features/search/SearchResultsGrid.svelte

- Extracts the media tag type as a separate tag component.
- Fixes the tags in the search results grid.
Before:
After:

fix(tags): use correct tags in search results grid
