trakt/trakt-web

- projects/client/src/lib/components/buttons/mark-as-watched/MarkAsWatchedActionButton.svelte
- projects/client/src/lib/components/buttons/mark-as-watched/MarkAsWatchedButton.svelte
- projects/client/src/lib/components/icons/MarkAsWatchedIcon.svelte
- projects/client/src/lib/components/icons/WatchlistIcon.svelte
- projects/client/test/mocks/IntersectionObserver.mock.ts
- projects/client/test/mocks/animate.mock.ts
- projects/client/test/mocks/matchMedia.mock.ts
- projects/client/vitest-setup.ts
This pull request, a whirlwind of button beautification and icon enchantment, descends upon the client project like a flamboyant UI artist armed with a palette of vibrant colors and a toolbox of CSS trickery. Observe, with a mix of admiration and bewilderment, the addition of media query sorcery, the refactoring of color and state logic, and the subtle yet impactful enhancements to button and icon components.
* The `MarkAsWatchedActionButton.svelte` and `MarkAsWatchedButton.svelte` components, those trusty companions for marking media milestones, undergo a transformation, their code infused with the magic of `useMedia` and `writable` stores. Color logic, once a rigid and inflexible entity, now dances to the tune of derived stores, its hues shifting dynamically based on the whims of the …
> feat: better states for add / remove depending on device

- projects/client/src/app.html
- projects/client/src/hooks.server.ts
- projects/client/src/lib/features/mobile-os/handle.ts
- projects/client/src/routes/+layout.svelte
- projects/client/src/style/scss/mixins/index.scss
@seferturan please look at this as is
BEFORE:
AFTER:
> feat(pwa): blend in with top bar

- projects/client/src/lib/sections/profile-banner/ProfilePageBanner.svelte
- projects/client/src/lib/sections/profile/components/ProfileContainer.svelte
The avatar on the profile page will now have the same position as the one on the dashboard.
> fix(profile): make avatar more consistent with avatar on dashboard

- projects/client/src/lib/features/auth/utils/decrypt.spec.ts
- projects/client/src/lib/features/auth/utils/encrypt.spec.ts
- projects/client/src/mocks/data/auth/encryptionKeyMock.ts
This pull request, a clandestine operation in the shadowy realm of encryption and decryption, infiltrates the `projects/client` directory, leaving a trail of renamed mocks and enhanced test coverage in its wake. Observe, with a mix of intrigue and suspicion, the meticulous refinement of utility functions and the relentless pursuit of code integrity.
* The `encryptionKeyMock.ts` file, once known by the less descriptive moniker `mockSessionKey.ts`, emerges from the shadows, its function now capable of accepting a `value` parameter, like a secret agent assuming a new identity. This enhancement, a subtle yet impactful change, provides greater flexibility in testing scenarios, allowing for the simulation of various encryption key values.
* The `decrypt.spec.ts` file, a battleground for code …
> test: add more decryption scenarios

- .deepsource.toml
- .github/workflows/ci.yml
- README.md
- projects/client/vite.config.ts
This pull request, a meticulous audit of code quality and a fervent embrace of automated analysis, ushers in the watchful eye of DeepSource, a digital sentinel tasked with scrutinizing every nook and cranny of the codebase. Observe, with a mix of anticipation and trepidation, the integration of this powerful tool, its tendrils reaching into configuration files and README badges, promising to enhance test coverage reporting and expose any lurking code quality issues.
* The `.deepsource.toml` file materializes, a cryptic configuration scroll, its purpose to summon the DeepSource analyzer and unleash its analytical powers upon the unsuspecting codebase. Test coverage, once a shadowy realm of uncertainty, is now brought into the harsh light of scrutiny, its secrets laid bare for all to see.
* …
> docs(readme): add deepsource badges

- .deepsource.toml
- projects/client/.scripts/cleanup-cloudflare.ts
- projects/client/.scripts/traktify-i18n.ts
- projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
- projects/client/src/lib/features/auth/requests/authorize.ts
- projects/client/src/lib/features/auth/utils/encrypt.ts
- projects/client/src/lib/features/cache-bust/handle.ts
- projects/client/src/lib/features/mobile-os/handle.ts
- projects/client/src/lib/requests/_internal/mapMovieResponseToMovieSummary.ts
- projects/client/src/lib/requests/_internal/mapShowResponseToShowSummary.ts
- projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
- projects/client/src/lib/requests/queries/shows/showPopularQuery.ts
- projects/client/src/lib/requests/queries/shows/showProgressQuery.ts
- projects/client/src/lib/requests/queries/shows/showRelatedQuery.ts
- projects/client/src/lib/requests/queries/shows/showTrendingQuery.ts
- projects/client/src/lib/sections/summary/components/MediaDetails.spec.ts
- projects/client/src/lib/stores/css/useMedia.ts
- projects/client/src/lib/stores/css/useVarToPixels.ts
- projects/client/src/lib/utils/actions/disableTransitionOn.spec.ts
- projects/client/src/lib/utils/assert/assertDefined.spec.ts
- projects/client/src/lib/utils/assert/assertDefined.ts
- projects/client/src/lib/utils/constants.ts
- projects/client/src/lib/utils/events/GlobalEventBus.ts
- projects/client/src/lib/utils/timing/debounce.ts
- projects/client/src/routes/movies/[slug]/+page.ts
- projects/client/src/routes/shows/[slug]/+page.ts
- projects/client/src/routes/shows/[slug]/seasons/[season]/episodes/[episode]/+page.ts
This pull request, a meticulous code inspection with a touch of obsessive-compulsive disorder, descends upon the client project like a swarm of nitpicky code reviewers armed with style guides and linting tools. Observe, with a mix of admiration and weariness, the bolstering of error handling, the tightening of type safety, and the relentless pursuit of code readability.
* The `traktify-i18n.ts` script, a translator of user interface text, now stands vigilant, its `assertDefined` incantation ensuring that the `GEMINI_API_KEY` environment variable is present and accounted for, preventing any unexpected crashes or translation mishaps.
* The `authorize.ts` function, a gatekeeper of user authentication, joins the error-handling crusade, its `assertDefined` checks verifying the presence of …
> refactor / cleanup detected code issues

- projects/api/src/index.ts
- projects/client/.scripts/delete-i18n.ts
- projects/client/src/lib/components/section-list/ListScrollHistoryProvider.svelte
- projects/client/src/lib/components/text/lineClamp.ts
- projects/client/src/lib/features/analytics/_internal/initialize.ts
- projects/client/src/lib/stores/useMarkAsWatched.spec.ts
- projects/client/src/lib/stores/useMarkAsWatched.ts
- projects/client/src/lib/stores/useWatchlist.spec.ts
- projects/client/src/lib/utils/constants.ts
- projects/client/src/lib/utils/store/resolve.spec.ts
- projects/client/src/lib/utils/store/resolve.ts
- projects/client/static/service-worker.js
- projects/client/test/mocks/matchMedia.mock.ts
- projects/client/test/readable/waitForEmission.ts
This pull request, a relentless crusade against code redundancy and a fervent celebration of consistency, descends upon the client project like a team of code janitors armed with lint rollers and style guides. Observe, with a mix of admiration and amusement, the introduction of the `NOOP_FN` constant, the meticulous refactoring of functions, and the subtle yet impactful enhancements to unit tests.
* The `NOOP_FN` constant emerges from the depths of the `constants.ts` file, a silent sentinel of nothingness, its purpose to represent the void of a no-operation function. This new addition, a testament to our obsessive pursuit of code reuse and efficiency, promises to replace countless empty functions with a single, elegant constant.
* The `lineClamp`, `initialize`, and `matchMedia.mock` …
> refactor / cleanup detected anti patterns 

- projects/client/.scripts/_internal/writeJsonFile.ts
- projects/client/src/lib/components/section-list/useScrollHistory.ts
- projects/client/src/lib/features/i18n/index.ts
- projects/client/src/lib/requests/queries/search/searchQuery.ts
- projects/client/src/lib/requests/queries/shows/showSeasonEpisodesQuery.ts
- projects/client/src/lib/sections/lists/stores/useStableArray.spec.ts
- projects/client/src/lib/stores/css/useMedia.ts
- projects/client/static/service-worker.js
- projects/client/test/mocks/animate.mock.ts
- projects/playground/src/createDeviceTokenPoller.ts
This pull request, a meticulous code inspection with a touch of obsessive-compulsive disorder, descends upon the project like a swarm of nitpicky code reviewers armed with style guides and linting tools. Observe, with a mix of admiration and weariness, the refinement of string concatenation, the tightening of type definitions, and the relentless pursuit of error-handling perfection.
* The `writeJsonFile.ts` script, a digital scribe tasked with the delicate art of JSON manipulation, now embraces the elegance of template literals, its string concatenation a symphony of backticks and placeholders.
* The `service-worker.js` file, a tireless guardian of cached resources, follows suit, its cache-busting query string concatenation now a model of clarity and conciseness, thanks to the magic of …
> refactor / eliminate remaining anti-patterns

- projects/client/src/lib/features/auth/utils/decrypt.spec.ts
- projects/client/src/lib/features/auth/utils/decrypt.ts
- projects/client/vite.config.ts
This pull request includes several changes to the `projects/client` directory, primarily focusing on improving test coverage and handling for errors in the decryption utility, as well as updating the Vite configuration for better CI integration.
* [`projects/client/src/lib/features/auth/utils/decrypt.spec.ts`](diffhunk://#diff-86b6047b61fca9759fd34d25a0e198371f2b56cf52b4cb579d3cc584eeb02557L4-R4): Added `vi` import from `vitest` and implemented `vi.spyOn` to mock `console.error` calls in test cases to ensure errors are logged correctly when decryption fails. [[1]](diffhunk://#diff-86b6047b61fca9759fd34d25a0e198371f2b56cf52b4cb579d3cc584eeb02557L4-R4) [[2]](diffhunk://#diff-86b6047b61fca9759fd34d25a0e198371f2b56cf52b4cb579d3cc584eeb02557R23-R40)
* …
> test / improve test reporting and fix decrypt testing

- projects/client/src/lib/features/auth/handle.spec.ts
- projects/client/src/lib/features/cache-bust/handle.spec.ts
- projects/client/src/lib/features/cache-bust/handle.ts
- projects/client/src/lib/features/gateway/handle.spec.ts
- projects/client/src/lib/features/i18n/handle.spec.ts
- projects/client/src/lib/features/i18n/handle.ts
- projects/client/src/mocks/data/auth/AuthMappedMock.ts
- projects/client/test/request/mockRequestEvent.ts
- projects/client/test/resolve/interceptHandleResolveOptions.ts
This pull request, a relentless crusade against code ambiguity and a fervent celebration of test-driven development, descends upon the project like a horde of QA engineers armed with automated test suites and bug-reporting arsenals. Observe, with a mix of admiration and trepidation, the meticulous refinement of test cases, the strategic deployment of mock data, and the subtle yet impactful enhancements to configuration and utility functions.
* The `handle.spec.ts` file, a battleground for authentication logic validation, undergoes a transformation, its test descriptions sharpened and its `Set-Cookie` header expectations refined to encompass a wider range of scenarios.
* The `handle.spec.ts` files for `cache-bust`, `gateway`, and `i18n` features, once barren wastelands of untested code, …
> test / more handles

- projects/client/src/lib/stores/_internal/toMarkAsWatchedPayload.spec.ts
- projects/client/src/lib/stores/_internal/toWatchlistPayload.spec.ts
- projects/client/src/lib/stores/css/computeVariable.spec.ts
- projects/client/src/lib/stores/css/useMedia.ts
This pull request, a relentless pursuit of code quality and a fervent celebration of test-driven development, descends upon the client project like a horde of QA engineers armed with automated test suites and bug-reporting arsenals. Observe, with a mix of admiration and trepidation, the meticulous construction of unit tests, the strategic refactoring of the `MediaQueryManager` class, and the subtle yet impactful enhancements to code structure and maintainability.
* The `toMarkAsWatchedPayload.spec.ts` file, a testing ground for payload generation, erupts with a barrage of assertions, its test cases meticulously examining the behavior of the `toMarkAsWatchedPayload` function under a variety of scenarios, ensuring that payloads are crafted with precision and accuracy.
* The …
> test / describe few more aspects

- projects/client/src/lib/components/text/ClampedTest.spec.ts
- projects/client/src/lib/components/text/ClampedText.svelte
- projects/client/src/lib/stores/useDebouncedValue.spec.ts
This pull request, a relentless pursuit of code quality and a fervent celebration of test-driven development, descends upon the client project like a horde of QA engineers armed with automated test suites and bug-reporting arsenals. Observe, with a mix of admiration and trepidation, the meticulous construction of test cases for the `ClampedText` and `useDebouncedValue` components, and the subtle yet impactful refinement of the `appendClassList` function.
* The `ClampedText.spec.ts` file, a testing ground for text truncation and styling, erupts with a barrage of assertions, its test cases meticulously examining the behavior of the `ClampedText` component under a variety of scenarios. Short text, long text, custom classes, line-clamp properties – all are subjected to the scrutiny of these …
> test / expand test suite

- projects/api/src/contracts/oauth/_internal/request/tokenBaseSchema.ts
- projects/api/src/contracts/oauth/_internal/request/tokenRefreshSchema.ts
- projects/api/src/contracts/oauth/_internal/request/tokenRequestSchema.ts
- projects/api/src/contracts/oauth/index.ts
- projects/client/src/lib/features/auth/handle.spec.ts
- projects/client/src/lib/features/auth/handle.ts
- projects/client/src/lib/features/auth/models/AuthToken.ts
- projects/client/src/lib/features/auth/requests/_internal/getGrantTypeAndCode.ts
- projects/client/src/lib/features/auth/requests/authorize.ts
- projects/client/src/lib/features/auth/requests/verifyAuth.ts
- projects/client/src/mocks/data/auth/EncryptedExpiredAuthMock.ts
> feat: auth token refresh

- projects/api/src/contracts/users/_internal/response/historyEpisodesResponseSchema.ts
- projects/api/src/contracts/users/index.ts
- projects/client/i18n/messages/de-de.json
- projects/client/i18n/messages/en.json
- projects/client/i18n/messages/es-es.json
- projects/client/i18n/messages/es-mx.json
- projects/client/i18n/messages/fr-ca.json
- projects/client/i18n/messages/fr-fr.json
- projects/client/i18n/messages/ja-jp.json
- projects/client/i18n/messages/nl-nl.json
- projects/client/i18n/messages/pl-pl.json
- projects/client/i18n/messages/pt-br.json
- projects/client/i18n/messages/ro-ro.json
- projects/client/i18n/messages/uk-ua.json
- projects/client/src/lib/requests/queries/users/episodeHistoryQuery.ts
- projects/client/src/lib/sections/lists/RecentlyWatchedList.svelte
- projects/client/src/lib/sections/lists/components/EpisodeItem.svelte
- projects/client/src/lib/sections/lists/stores/useRecentlyWatchedList.ts
- projects/client/src/lib/sections/profile/Profile.svelte
> feat: show recently watched episodes in profile page

- .github/workflows/cloudflare-cleanse.yml
- projects/client/.scripts/cleanse-cloudflare.ts
- projects/client/package.json
This pull request introduces a scheduled GitHub Actions workflow to automate the cleansing of Cloudflare deployments and ensures consistency in naming conventions across related scripts and functions.
- Added a new GitHub Actions workflow named "The Cloudflare Purgation Ritual" to automate the cleansing task. This workflow is scheduled to run every other Sunday at 00:00 and can also be triggered manually.
- Renamed the `cleanup-cloudflare.ts` script to `cleanse-cloudflare.ts` to better reflect its purpose.
- Renamed the `cleanupDeployments` function within the script to `cleanseDeployments` to maintain consistency in naming conventions.
- Updated the corresponding script command in `package.json` from `cloudflare:cleanup` to `cloudflare:cleanse` to match the renamed script.
(These …
> ci: define bi-weekly scheduled cloudflare deployment cleanse

- projects/client/i18n/messages/pl-pl.json
Small, perhaps pedantic, thing but the inconsistent verb aspect can be seen in different messages on a single (profile) page which makes this a bit worse imo.
> chore: use perfective aspect for 'Recently Watched' messages in Polish

- projects/api/src/contracts/_internal/response/characterResponseSchema.ts
- projects/api/src/contracts/_internal/response/peopleResponseSchema.ts
- projects/api/src/contracts/people/_internal/response/peopleMovieCreditsResponseSchema.ts
- projects/api/src/contracts/people/_internal/response/peopleShowCreditsResponseSchema.ts
- projects/api/src/contracts/people/index.ts
- projects/client/src/lib/requests/models/PersonSummary.ts
- projects/client/src/lib/requests/queries/people/peopleMovieCreditsQuery.ts
- projects/client/src/lib/requests/queries/people/peopleShowCreditsQuery.ts
- projects/client/src/lib/requests/queries/people/peopleSummaryQuery.ts
- projects/client/src/lib/sections/lists/CreditsList.svelte
- projects/client/src/lib/sections/lists/stores/useCreditsList.ts
- projects/client/src/lib/sections/summary/PeopleSummary.svelte
- projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloPersonMappedMock.ts
- Unfortunately no sorting support in the API 😢
> feat: add credits to cast summary page

- projects/client/src/lib/utils/actions/triggerWithTouch.spec.ts
- projects/client/src/lib/utils/actions/triggerWithTouch.ts
This pull request refines the `triggerWithTouch` utility function, enhancing its handling of touch events on iOS devices and preventing unintended click activations.
- Introduced a `MOVE_THRESHOLD_PIXELS` constant to define the sensitivity of touch movement detection. This threshold helps distinguish between intentional taps and accidental swipes or drags.
- Added state management to track the initial touch position and calculate the movement delta, providing a more accurate assessment of user interaction.
- Replaced the `pointerup` event listener with `touchstart` and `touchend` listeners, specifically tailored for touch-based interactions on iOS devices.
- Implemented helper functions `getPosition` and `getDelta` to calculate touch positions and movement deltas, improving code …
> fix: improve the ios hack using pointer events and doing delta matches

- projects/client/src/app.d.ts
- projects/client/src/lib/features/query/QueryClientProvider.svelte
- projects/client/vite.config.ts
- Define `zod` schemas for mapped data models to ensure data integrity and consistency.
- Generate a hash based on the response model to uniquely identify each query.
- Incorporate the mapped model hash into the query key for more precise cache invalidation.
This pull request enhances the query client's persistence mechanism and introduces a dynamic query buster to improve cache management and data freshness.
- Added a `buster` property to the `persistOptions` in the `QueryClientProvider` component. This property incorporates the `TRAKT_QUERY_BUSTER` value, allowing for more granular control over query persistence and cache invalidation.
- Introduced the `TRAKT_QUERY_BUSTER` environment variable in the `vite.config.ts` file. This variable is dynamically generated using …
> feat: bust persistent cache on new builds

- projects/client/src/lib/sections/navbar/Navbar.svelte
- projects/client/src/lib/sections/navbar/ProfileButton.svelte
Fixes https://github.com/trakt/trakt-lite/issues/325
Before:
After:
> fix(navbar): fix buttons overflowing on tablet size

- projects/client/src/lib/components/card/CardFooter.svelte
- projects/client/src/style/layout/index.css
This pull request focuses on enhancing the visual appeal and consistency of card components by adjusting their styles and layout dimensions.
- Updated the `.card-footer-information` class to have full width, a top margin, and hidden overflow. This change improves the layout and readability of the card footer information.
- Adjusted the global child element styles within the card footer to ensure proper alignment and spacing, enhancing the visual organization of the footer content.
- Modified the height of `poster-card`, `show-card`, and `episode-card` to new values in the layout styles. This adjustment ensures better layout consistency and visual harmony across different card types.
(These changes, like a meticulous artist refining their brushstrokes, enhance the visual appeal and …
> fix(card): update card sizing and condense footer

- projects/api/src/contracts/_internal/response/upNextSortBySchema.ts
- projects/api/src/contracts/enums/index.ts
- projects/api/src/contracts/enums/upNextSortOptionSchema.ts
- projects/api/src/contracts/users/_internal/response/settingsResponseSchema.ts
- projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
This pull request refines the handling of user settings and introduces a new schema for sorting options to improve the user experience and streamline development.
- The application will now prioritize default behaviors over granular user settings. This strategic decision allows for greater flexibility in development and ensures a more consistent user experience, especially in the early stages of the project.
- User settings, such as sorting options, may be reintroduced later as local filtering/sorting mechanisms or after the main release, providing users with more personalized control over their experience.
- Added a new schema, `upNextSortBySchema`, to define and validate sorting options for media lists. This schema ensures data integrity and consistency when handling user preferences …
> feat / prefer default behaviors and support only basic settings

- projects/client/src/app.d.ts
- projects/client/src/lib/components/background/CoverImage.svelte
- projects/client/src/lib/features/image/components/CrossOriginImage.svelte
- projects/client/src/routes/+layout.svelte
This pull request focuses on improving the loading performance of the application by optimizing the handling of images and fonts.
- The `CoverImage.svelte` component now uses `loading="eager"` for background images, ensuring they are loaded immediately to prevent visual delays and improve the perceived loading speed.
- The `CrossOriginImage.svelte` component has been updated to use `loading="lazy"` by default. This defers the loading of images until they are needed, improving initial page load performance and reducing unnecessary resource consumption.
- The `+layout.svelte` file now includes `rel="preload"` and `as="style"` attributes for the font link, allowing the browser to preload the font file and improve the rendering speed of text elements.
- A script has been added to switch the …
> perf / address some first-load and LCP issues 

- projects/client/src/lib/features/query/QueryClientProvider.svelte
- projects/client/src/lib/features/query/createPersister.ts
- projects/client/src/lib/features/query/idbPersisterFactory.ts
- projects/client/src/lib/features/spoilers/useSpoiler.ts
- projects/client/src/lib/sections/lists/stores/useCalendarEpisodes.ts
- projects/client/src/lib/sections/lists/stores/useFavoritesList.ts
- projects/client/src/lib/sections/lists/stores/useSeasonEpisodes.ts
- projects/client/src/lib/sections/lists/stores/useUpNextEpisodes.ts
- projects/client/src/lib/sections/lists/watchlist/useWatchlistList.ts
- projects/client/src/lib/stores/useWatchNow.ts
- projects/client/src/lib/utils/perf/monitor.ts
- projects/client/src/lib/utils/requests/toLoadingState.ts
- projects/client/src/routes/+layout.ts
- projects/client/static/service-worker.js
This pull request focuses on improving performance monitoring, simplifying state derivation, and enhancing caching strategies within the client project.
- Introduced a `monitor` function to wrap `persistClient` and `restoreClient` methods in the `idbPersisterFactory`. This allows for performance monitoring of these operations, providing insights into potential bottlenecks or areas for optimization.
- Added a generic `monitor` utility function to log the execution time of functions in non-production environments. This helps identify performance issues during development and testing.
- Replaced custom loading state derivation logic in various components with the `toLoadingState` utility function. This simplifies the code and promotes consistency in handling loading states across the …
> perf / various improvements for first load

- .github/workflows/ci.yml
- projects/client/src/app.d.ts
- projects/client/src/lib/features/auth/handle.ts
- projects/client/src/lib/features/auth/stores/useAuth.ts
- projects/client/src/lib/utils/perf/monitor.ts
This pull request focuses on updating the CI workflow, improving error handling, and enhancing type safety in the client project.
- Updated the Deno version specification in the CI workflow to use the latest version within the 2.x range. This ensures that the CI environment stays up-to-date with the latest Deno features and bug fixes while maintaining compatibility within the major version.
- Simplified error handling in the `getLegacyAuthCookie` function by using a catch-all variable `_` instead of `error`. This change improves code readability without sacrificing functionality.
- Replaced `window.location` with `globalThis.location` in the `useAuth.ts` file to ensure compatibility across different environments, including server-side rendering and browser contexts.
- Enhanced the …
> chore / use deno stable and address cq & lint issues

- projects/client/src/lib/components/buttons/Button.svelte
- Scaling works well when the width and height are equal, but with dynamic widths, layouting with small buttons is not good.
- Small buttons will now have the exact height of an action button
Before:
After:
> refactor(button): small buttons without scaling

- projects/client/src/lib/components/lists/grid-list/GridList.svelte
- projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte
- projects/client/src/lib/sections/summary/components/overlay/TrailerOverlay.svelte
- If there is no watch now link, use the trailer as the poster action.
> feat(summary): play trailer if there is no watch now link

- projects/client/src/lib/components/episode/tags/EpisodeStatusTag.spec.ts
- projects/client/src/lib/components/episode/tags/ShowProgressTag.spec.ts
- projects/client/src/lib/components/episode/tags/ShowProgressTag.svelte
- projects/client/src/lib/components/media/tags/AirDateTag.spec.ts
This pull request focuses on improving the test coverage of various components and enhancing the accessibility of the `ShowProgressTag` component.
- Added comprehensive test cases for the `EpisodeStatusTag` component, covering different episode status scenarios such as full season, season finale, series finale, mid-season finale, and various premieres.
- Added test cases for the `ShowProgressTag` component, verifying its rendering with different progress values, including 0%, 50%, 100%, and decimal values.
- Added test cases for the `AirDateTag` component, ensuring it correctly displays air dates for various scenarios, including null year, past year, and future dates (upcoming week, month, 3 months, 6 months, and year).
- Added accessibility attributes (`role="progressbar"`, …
> test / tags with logic

- projects/client/src/lib/components/card/CardFooter.svelte
- projects/client/src/lib/sections/lists/components/MediaSummaryCard.svelte
- projects/client/src/style/layout/index.css
This pull request refines the styling and layout of card components, particularly the `CardFooter` and `MediaSummaryCard`, to enhance visual consistency and maintainability.
- Renamed CSS classes in the `CardFooter` component to follow a consistent naming convention using the `trakt-` prefix. This improves code readability and organization.
- Added new layout variables (`--height-card` and `--width-card`) to the `Card` component in the `MediaSummaryCard` component. This allows for more flexible and centralized control over card dimensions.
- Updated global styles for `trakt-card` and `trakt-card-footer` classes to ensure proper alignment and spacing within the card layout.
- Added new CSS variables (`--width-summary-card` and `--height-summary-card`) for summary card dimensions in the …
> feat / allow scroll restoration when navigating back on mobile (view all)

- projects/client/src/lib/components/summary/SummaryPoster.svelte
https://github.com/user-attachments/assets/e12ad17d-3c7a-4a1b-bef7-535eb96070e0
> fix(summary): scale poster overlay together with the border

- projects/client/src/lib/components/summary/RatingList.svelte
- projects/client/src/lib/sections/summary/components/media/MediaMetaInfo.svelte
- projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte
This pull request refines the handling of derived state in several components, ensuring that changes in data are reflected reactively in the user interface.
- Replaced direct function calls with the `$derived` store in the following components:
- `RatingList.svelte`: Ensures that the display of ratings updates reactively when the underlying data changes.
- `MediaMetaInfo.svelte`: Ensures that the "Watch Now" information updates reactively based on the latest data.
- `MediaSummary.svelte`: Ensures that the media summary information, including "Watch Now" details, updates reactively in response to data changes.
(This change, like a vigilant detective constantly observing their surroundings, ensures that the user interface remains synchronized with the underlying data. By leveraging the …
> fix(summary): ensure state is updated when navigating back/forth

- projects/client/src/lib/requests/queries/search/searchQuery.ts
- projects/client/src/lib/sections/summary/components/media/MediaSummaryItem.svelte
This pull request improves the handling of media entries and enhances the user interface for a more informative and consistent experience.
- Refined the `isGarbage` function in `searchQuery.ts` to better identify invalid media entries. The updated function checks for missing or invalid data, such as unreleased status, missing year, and empty genres, ensuring that only relevant and complete media entries are displayed in search results.
- Updated the `MediaSummaryItem.svelte` component to use the `i18n` messages module for translations, ensuring that the UI elements are properly localized for different languages.
- Modified the media title display to show a "TBA" (To Be Announced) label if the year is not available, providing clearer information to users about upcoming or unreleased media. …
> fix(search): improve garbage filter

- projects/client/src/lib/sections/navbar/Navbar.svelte
- projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
This pull request enhances the search input component in the navbar, improving its layout, transitions, and responsiveness, particularly on mobile devices.
- Added new CSS variables and styles to control the search input width on mobile devices. This ensures that the search input adapts seamlessly to smaller screens and provides a better user experience on mobile.
- Adjusted the display properties and positioning of the search input to ensure it occupies the full width and height of its container on mobile devices, maximizing screen real estate and providing a more immersive search experience.
- Refined the layout and transitions of the search input to ensure smooth and visually appealing transitions between different states (e.g., focused, unfocused).
- Increased the `z-index` value of …
> feat(search): expand on mobile

- projects/client/src/lib/features/mobile-os/handle.spec.ts
- projects/client/src/lib/features/mobile-os/handle.ts
- projects/client/src/lib/features/theme/handle.spec.ts
- projects/client/src/lib/features/theme/handle.ts
- projects/client/src/lib/features/theme/utils/coerceTheme.spec.ts
- projects/client/test/resolve/interceptHandleResolveOptions.ts
Adds test for the theme and mobile-os handle hooks
> test: handles

- .vscode/settings.json
- commitlint.config.js
- deno.lock
- projects/client/package.json
- projects/client/src/app.d.ts
- projects/client/src/app.html
- projects/client/src/lib/features/analytics/AnalyticsProps.ts
- projects/client/src/lib/features/analytics/FirebaseSetup.svelte
- projects/client/src/lib/features/analytics/PageView.svelte
- projects/client/src/lib/features/analytics/PostHogSetup.svelte
- projects/client/src/lib/features/analytics/_internal/loader/AnalyticsLoader.svelte
- projects/client/src/lib/features/analytics/_internal/loader/AnalyticsProps.ts
- projects/client/src/lib/features/analytics/_internal/loader/AnonymousAnalytics.svelte
- projects/client/src/lib/features/analytics/_internal/loader/UserAnalytics.svelte
- projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
- projects/client/src/mocks/data/users/mapped/ExtendedUserSettingsMappedMock.ts
- projects/client/vite.config.ts
This pull request introduces significant changes to the analytics system and adds support for PostHog analytics. The most important changes include updating configuration files, modifying existing components to integrate PostHog, and refactoring the analytics components for better modularity.
* [`projects/client/src/lib/features/analytics/AnalyticsProvider.svelte`](diffhunk://#diff-29a2387908228541eedf1a65c4a576138a2dd7a6200b1ede877aaadc6ae5df8fR4-R17): Added `FirebaseSetup` and `PostHogSetup` components to initialize and configure analytics providers.
* [`projects/client/src/lib/features/analytics/PostHogSetup.svelte`](diffhunk://#diff-f8ca1432e1ec217696da3d1847e7a600218a67d7f3374c6ab7a7aced7d4dfaf0R1-R33): Created a new component to initialize PostHog analytics and handle user …
> feat / configure posthawg

- projects/client/src/lib/requests/_internal/mapShowResponseToEpisodeCount.ts
- projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
- projects/client/src/lib/requests/queries/shows/showRelatedQuery.ts
- projects/client/src/lib/requests/queries/shows/showTrendingQuery.ts
- projects/client/src/lib/requests/queries/users/showWatchlistQuery.ts
- projects/client/src/lib/sections/lists/watchlist/useWatchlistList.ts
- projects/client/src/mocks/data/users/mapped/WatchlistShowsMappedMock.ts
- Also add episode counts to shows on the watchlist.
Before:
After:
> fix: show episode counts on watchlisted shows

- projects/client/src/lib/sections/media-actions/mark-as-watched/useMarkAsWatched.ts
- projects/client/src/lib/sections/media-actions/watchlist/useWatchlist.ts
Before:
https://github.com/user-attachments/assets/404d9e74-0763-4ed3-9f57-81c75532053c
After:
https://github.com/user-attachments/assets/9ecaef39-e001-487b-9285-9ff01fb8d71f
> fix: keep actions disabled until handled

- projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
- projects/client/src/lib/sections/lists/social/SocialActivityCard.svelte
> feat(social): add username in profile badge

- projects/api/src/contracts/users/_internal/request/listParamsSchema.ts
- projects/api/src/contracts/users/index.ts
- projects/client/src/lib/requests/queries/users/listItemsQuery.spec.ts
- projects/client/src/lib/requests/queries/users/listItemsQuery.ts
- projects/client/src/lib/requests/queries/users/listSummaryQuery.spec.ts
- projects/client/src/lib/requests/queries/users/listSummaryQuery.ts
- projects/client/src/lib/sections/lists/userlist/UserlistList.svelte
- projects/client/src/lib/sections/lists/userlist/useUserlistList.ts
- projects/client/src/lib/sections/summary/components/lists/_internal/ListHeader.svelte
- projects/client/src/lib/sections/summary/components/lists/_internal/ListPosters.svelte
- projects/client/src/lib/sections/summary/components/lists/_internal/ListSummaryCard.svelte
- projects/client/src/lib/utils/url/UrlBuilder.ts
- projects/client/src/mocks/data/lists/mapped/ListedMoviesMappedMock.ts
- projects/client/src/mocks/data/lists/response/ListedMoviesResponseMock.ts
- projects/client/src/mocks/handlers/users.ts
- projects/client/src/routes/users/[user]/lists/[list]/+page.svelte
- projects/client/src/routes/users/[user]/lists/[list]/_internal/mapToMediaType.ts
- projects/client/src/routes/users/[user]/lists/[list]/useListSummary.ts
- Add possibility to view lists.
- When clicking on a popular list from a movie summary page, it will show the movies on that list.
- When clicking on a popular list from a show summary page, it will show the shows on that list.
- Will need a follow-up to display all items on a list (deal with pagination).
https://github.com/user-attachments/assets/cc0e0d7a-c4b2-446c-afc9-e71e4e27bc02
> Feat / view lists

- projects/client/src/lib/sections/navbar/Navbar.svelte
This pull request modifies the `Navbar.svelte` component to improve its rendering logic based on device type. The key change is the introduction of a `device` attribute within the `RenderFor` component.
* **`Navbar.svelte`**: The `RenderFor` component now includes a `device` attribute. This attribute accepts an array of device types, such as `["tablet-sm", "tablet-lg", "desktop"]`, allowing developers to precisely control which elements are rendered on specific devices.  This enhancement provides greater flexibility and control over the navbar's layout and content based on screen size.
(This update, like a detective using specialized tools for different clues, adds a layer of precision to the navbar's rendering. The `device` attribute allows us to tailor the user experience to specific …
> feat(navbar): hide logo on mobile

- projects/client/src/lib/requests/_internal/mapToMovieEntry.ts
- projects/client/src/lib/requests/_internal/mapToShowEntry.ts
- projects/client/src/lib/requests/models/MediaEntry.ts
- projects/client/src/lib/sections/lists/CreditsList.svelte
- projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticMappedMock.ts
- projects/client/src/mocks/data/summary/movies/matrix/MovieMatrixMappedMock.ts
- projects/client/src/mocks/data/summary/shows/devs/ShowDevsMappedMock.ts
- projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloMappedMock.ts
- projects/client/src/mocks/data/users/mapped/WatchlistMoviesMappedMock.ts
- projects/client/src/mocks/data/users/mapped/WatchlistShowsMappedMock.ts
- Sorts people credits by popularity.
Before:
After:
> Feat / sort credits by popularity

- projects/client/src/lib/components/buttons/Button.svelte
- projects/client/src/lib/components/dropdown/DropdownList.svelte
- projects/client/src/lib/sections/lists/SeasonList.svelte
- projects/client/src/lib/sections/navbar/Navbar.svelte
- projects/client/src/lib/sections/navbar/ProfileButton.svelte
- projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
- projects/client/src/style/layout/index.css
This pull request focuses on refining the styling and layout of various components within the `projects/client/src/lib` directory. The key changes include adjustments to button styles, dropdown list margins, navbar padding, and search input scaling.
* **`Button.svelte`**: The styles for buttons have been updated, including adjustments to height, border-radius, margin, and transform scale. These changes affect different button sizes and styles, ensuring a consistent and visually appealing appearance across the application.
* **`DropdownList.svelte`**: The margin for dropdown lists has been updated to include negative padding. This adjustment improves the alignment of dropdown lists within the layout.
* **`Navbar.svelte`**: The padding and height of the navbar have been adjusted using new …
> feat / various spacing improvements

- projects/client/src/lib/components/buttons/_internal/useDangerButton.spec.ts
- projects/client/src/lib/sections/lists/recommended/useRecommendedList.ts
- projects/client/src/lib/sections/lists/stores/useDailyOrderArray.spec.ts
- projects/client/src/lib/sections/lists/stores/useDailyOrderArray.ts
- projects/client/src/lib/stores/useActiveLink.spec.ts
- projects/client/test/mocks/ls.mock.ts
- projects/client/vitest-setup.ts
This pull request introduces enhancements to the recommended list functionality and improves the testing setup. The primary goal is to maintain a stable daily order for recommended items, preventing the list from jumping around when users interact with it.
* **`useDailyOrderArray` Hook**: A new hook, `useDailyOrderArray`, has been implemented to manage the order of recommended items on a daily basis. This hook utilizes local storage to store the order, ensuring that it remains consistent throughout the day, even if the user interacts with the list by watchlisting or marking items as watched.
* **`useRecommendedList` Integration**: The `useRecommendedList` function has been updated to utilize the `useDailyOrderArray` hook. This integration ensures that the recommended list maintains a …
> feat / stable recommendation order

- projects/client/src/lib/sections/navbar/Navbar.svelte
Didnt have time to verify actual mobile devices yet.
Before:
https://github.com/user-attachments/assets/a8a8d4ce-0e6b-4a59-baf6-3713a88a7a40
After:
https://github.com/user-attachments/assets/0f8746ae-98cf-4d37-aacd-67810ae3605c
> feat(navbar): float after scroll

- projects/client/src/lib/sections/lists/SeasonList.svelte
- Active season in season list could be wrong:
- Go to a show with few seasons, for example something with only one season. Let's call it `show x`
- The active season is set to the first season.
- From related shows, click on one with many seasons, where the user has seen more than 1 season. Let's call it `show y`.
- The active season is set to where the user has left off watching. For example season 2.
- Navigate back: `show x` will now show the state of `show y`.
- See below for a visual example
https://github.com/user-attachments/assets/faa8a3f0-c786-411e-9dd8-99b989994a9e
> fix(list): reset last watched season

- projects/client/src/lib/components/buttons/popup/_internal/bodyPortal.ts
- projects/client/src/lib/components/buttons/popup/_internal/usePortal.spec.ts
- Fixes opening the popup menu on Android when scrolled down.
Before:
https://github.com/user-attachments/assets/7da6fecb-1b95-403b-a8d3-e47297a98ae6
After:
https://github.com/user-attachments/assets/50ea02de-2e01-4ffe-87e0-f8ec3b324181
> fix(popup): set at proper position

- projects/client/src/lib/sections/summary/components/rating/RateNow.svelte
- Reserves space for the ratings to get rid of jumps.
https://github.com/user-attachments/assets/de777005-db3d-4961-a611-88853ea4b25f
> fix(summary): reserve space for ratings

- projects/client/src/lib/sections/lists/components/ActivityCard.svelte
- projects/client/src/lib/sections/lists/components/ActivitySummaryCard.svelte
- projects/client/src/lib/sections/lists/components/EpisodeCard.svelte
- projects/client/src/lib/sections/lists/history/RecentlyWatchedItem.svelte
- projects/client/src/lib/sections/lists/social/SocialActivityItem.svelte
- projects/client/src/lib/sections/summary/components/media/MediaSummaryItem.svelte
This pull request focuses on refactoring and improving the `projects/client/src/lib/sections/lists` components. The changes include renaming files, updating imports, modifying component properties, and adjusting the layout of components.
* **`ActivityCard.svelte` and `ActivitySummaryCard.svelte`**: The `SocialActivityCard.svelte` and `SocialActivitySummaryCard.svelte` files have been renamed to `ActivityCard.svelte` and `ActivitySummaryCard.svelte`, respectively. The corresponding imports in other files have been updated to reflect these changes. This renaming improves consistency and clarity in the component naming conventions.
* **`activityAt` Property**: The `ActivityCard.svelte` and `ActivitySummaryCard.svelte` components now use a new `activityAt` property instead of accessing …
> fix / improve mobile view for episode summaries 

- commitlint.config.js
- projects/client/i18n/messages/ro-ro.json
- projects/client/i18n/messages/uk-ua.json
- projects/client/src/lib/utils/formatting/date/toHumanDuration.spec.ts
- projects/client/src/lib/utils/formatting/date/toHumanDuration.ts
This pull request introduces several improvements to the `toHumanDuration` function, updates localization files, and adds a new formatter to the codebase.
* **Range Checks**: New range checks (`isDaysRange`, `isHoursRange`, `isMinutesRange`) have been added to the `toHumanDuration` function to improve the logic for formatting durations. These checks provide a more precise and efficient way to determine the appropriate formatting for different time ranges.
* **Conditional Updates**: The conditions within the function have been updated to utilize the new range checks, ensuring that the formatted duration parts are correctly assembled.
* **Test Case Modifications**: The test cases for the `toHumanDuration` function have been modified to reflect the updated logic and to cover edge cases and …
> feat / improve progress reporting for smaller devices and multiple locales

- projects/client/src/lib/components/link/Link.svelte
> fix(safari): use mobile apple hack also for link components

- projects/client/src/app.d.ts
- projects/client/src/app.html
- projects/client/src/hooks.server.ts
- projects/client/src/lib/features/deployment/DeploymentEndpoint.ts
- projects/client/src/lib/features/deployment/handle.ts
- projects/client/src/routes/+layout.svelte
- projects/client/vite.config.ts
This pull request introduces changes to enhance the deployment process by adding deployment SHA handling and improving related functionalities.
* **`handleDeployment` Handler**: A new handler, `handleDeployment`, has been added to manage deployment-related requests. This handler ensures that deployment information is properly processed and routed.
* **Deployment SHA Endpoint**: A new endpoint has been introduced to handle requests for the deployment SHA. This endpoint allows the application to easily retrieve and utilize the deployment SHA information.
* **HTML Template Update**: The HTML template has been updated to include a new data attribute, `data-deployment-sha`, which stores the deployment SHA. This makes the deployment SHA accessible to the client-side application.
* **Vite …
> feat: bust navigation cache on new deployment

- deno.lock
- projects/client/package.json
- projects/client/src/lib/requests/queries/users/hiddenShowsQuery.ts
- projects/client/src/lib/requests/sync/markAsWatchedRequest.ts
- projects/client/src/lib/requests/sync/removeWatchedRequest.ts
- Update to api v0.1.4
- We no longer have to filter out hidden seasons; api returns correct response now.
- Makes it possible to:
- Remove individual history items.
- Get history of specific items.
> chore: update trakt-api to 0.1.4

- projects/client/i18n/messages/de-de.json
- projects/client/i18n/messages/en.json
- projects/client/i18n/messages/es-es.json
- projects/client/i18n/messages/es-mx.json
- projects/client/i18n/messages/fr-ca.json
- projects/client/i18n/messages/fr-fr.json
- projects/client/i18n/messages/it-it.json
- projects/client/i18n/messages/ja-jp.json
- projects/client/i18n/messages/nl-nl.json
- projects/client/i18n/messages/pl-pl.json
- projects/client/i18n/messages/pt-br.json
- projects/client/i18n/messages/ro-ro.json
- projects/client/i18n/messages/uk-ua.json
- projects/client/src/app.d.ts
- projects/client/src/lib/components/link/Link.svelte
- projects/client/src/lib/sections/navbar/Navbar.svelte
- projects/client/src/lib/sections/navbar/ProfileButton.svelte
- projects/client/src/lib/sections/navbar/components/GetVIPLink.svelte
- projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
- Fist step in new navbar design:
- New VIP upsell link
- Also relocates the lite switch on mobile
Before/after:
Before/after:
> Feat/ new vip badge

- projects/client/src/lib/components/dialogs/Dialog.svelte
> fix(dialog): open state in safari

- projects/client/src/lib/sections/lists/streaming/StreamingList.svelte
- Hide the streaming picks if a user has no favorite services.
> fix(list): only show streaming list when user has favorite services

- projects/client/src/lib/components/background/CoverImage.svelte
- projects/client/src/lib/components/background/TraktCoverImage.svelte
- projects/client/src/lib/components/card/CardCover.svelte
- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
- projects/client/src/style/theme/global.css
- projects/client/src/style/theme/modes.css
- shadows for card covers
- shadows for list
- cover image and logo cover are now grayscale to blend into the background better
- card background
TODO (part #2):
- chips / tags
- secondary buttons
> feat / light theme part #1

- projects/client/src/lib/components/buttons/Button.svelte
- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
- projects/client/src/lib/sections/lists/social/SocialActivityItem.svelte
- projects/client/src/style/theme/global.css
- projects/client/src/style/theme/modes.css
- improve social activity username
- update affected tags
- update button tag style
Did not do:
- technically button should be purple-100 on light mode but only for background, this currently is not a trivial change since foreground / background swap in certain states (eg: hover) and that ends up looking bad / low contrast
> feat / light theme #2

- projects/client/src/lib/components/card/CardFooter.svelte
- projects/client/src/lib/sections/lists/streaming/StreamingList.svelte
- projects/client/src/lib/sections/navbar/components/search/SearchInput.svelte
- projects/client/src/style/theme/global.css
- projects/client/src/style/theme/modes.css
- add initial version for navbar theme
- since I didn't update secondary colors I opted for going with a shadow under actions
- stylize input in navbar
TODO:
- tomorrow I will add auto support since Light mode is now looking quite good
> feat / light theme #3

- projects/client/src/lib/sections/landing/Landing.svelte
- projects/client/src/lib/sections/landing/components/JoinForFreeButton.svelte
- Makes the button on the landing page also reachable using the dpad controller
> feat(landing): support dpad navigation

- projects/client/src/lib/features/auth/handle.ts
Keep the auth cookie for a bit longer.
> fix(auth): keep cookie stored longer

- projects/client/src/app.d.ts
- projects/client/src/lib/components/card/CardCover.svelte
- projects/client/src/lib/components/card/CardCoverProps.ts
- projects/client/src/lib/features/image/components/CrossOriginImage.svelte
- projects/client/src/lib/sections/lists/components/CastMemberCard.svelte
- projects/client/src/lib/sections/lists/components/EpisodeItemCard.svelte
- projects/client/src/lib/sections/lists/components/MediaItemCard.svelte
> feat: undercover titlte

- projects/client/src/lib/features/parameters/appendGlobalParameters.ts
- Do not consider external links when appending global parameters
> fix(parameter): do not modify external links

- projects/client/src/lib/components/card/Card.svelte
- projects/client/src/lib/components/link/Link.svelte
- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
- projects/client/src/lib/sections/lists/components/CastMemberCard.svelte
- New focus effect for cars when navigating with dpad
Before:
https://github.com/user-attachments/assets/06d88f43-24ce-4756-88ea-1e23d0988fbf
After:
https://github.com/user-attachments/assets/0ad69dde-f728-4947-8e1f-e1c53b8bb7d3
> feat(navigation): zoomed in card focus state when navigating with dpad

- projects/client/src/routes/auth/device/+page.svelte
- projects/client/src/routes/auth/device/_internal/QrCode.svelte
- Footer no longer jumps as the authentication data is being loaded.
- Was very noticeable on an actual device 😅
> fix(auth): give qr code container a static height

- projects/client/src/lib/components/lists/_internal/ListHeader.svelte
- projects/client/src/lib/components/lists/section-list/CollapseIcon.svelte
- projects/client/src/lib/components/lists/section-list/ExpandIcon.svelte
- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
https://github.com/user-attachments/assets/2ce41edd-a03b-49c4-891b-4ebf4455a714
https://github.com/user-attachments/assets/f26ca7fc-31eb-4659-bca2-f0c25da3c352
> feat(list): add support for collapse expand

- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
Before:
https://github.com/user-attachments/assets/d7a0b119-70ca-4a49-bd90-b6330c0990fd
After:
https://github.com/user-attachments/assets/b9ab2089-c3a4-4b2e-b71e-2a77c2abd1f6
> fix(list): animate list collapsed state only after mounting

- projects/client/src/lib/features/search/SearchInput.svelte
- projects/client/src/lib/features/search/SearchProvider.svelte
- projects/client/src/lib/features/search/_internal/SEARCH_CONTEXT_KEY.ts
- projects/client/src/lib/features/search/_internal/createSearchContext.ts
- projects/client/src/lib/features/search/_internal/getSearchContext.ts
- projects/client/src/lib/features/search/_internal/searchKeyFactory.ts
- projects/client/src/lib/features/search/useSearch.spec.ts
- projects/client/src/lib/features/search/useSearch.ts
- projects/client/src/lib/requests/queries/search/searchQuery.spec.ts
- projects/client/src/lib/requests/queries/search/searchQuery.ts
- projects/client/src/routes/+layout.svelte
- projects/client/src/routes/search/+page.svelte
- projects/client/test/beds/_internal/TestProvider.svelte
Follow-ups (most likely next week):
- Add People support
- Add `View All` per category
> feat(search): split results into movies and shows

- projects/client/src/lib/components/background/CoverImage.svelte
- projects/client/src/lib/components/background/CoverImageSetter.svelte
- projects/client/src/lib/components/background/_internal/useCover.ts
- projects/client/src/lib/requests/_internal/mapToColors.ts
- projects/client/src/lib/requests/_internal/mapToMovieEntry.ts
- projects/client/src/lib/requests/_internal/mapToShowEntry.ts
- projects/client/src/lib/requests/models/MediaEntry.ts
- projects/client/src/lib/requests/queries/movies/movieSummaryQuery.ts
- projects/client/src/lib/requests/queries/shows/showSummaryQuery.ts
- projects/client/src/lib/requests/queries/users/hiddenShowsQuery.spec.ts
- projects/client/src/lib/sections/summary/EpisodeSummary.svelte
- projects/client/src/lib/sections/summary/components/media/MediaSummary.svelte
- projects/client/src/mocks/data/lists/mapped/AllListedShowsMappedMock.ts
- projects/client/src/mocks/data/summary/movies/heretic/mapped/MovieHereticMappedMock.ts
- projects/client/src/mocks/data/summary/movies/heretic/response/MovieHereticResponseMock.ts
- projects/client/src/mocks/data/summary/movies/matrix/MovieMatrixMappedMock.ts
- projects/client/src/mocks/data/summary/movies/matrix/MovieMatrixResponseMock.ts
- projects/client/src/mocks/data/summary/shows/devs/ShowDevsMappedMock.ts
- projects/client/src/mocks/data/summary/shows/devs/ShowDevsResponseMock.ts
- projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloMappedMock.ts
- projects/client/src/mocks/data/summary/shows/silo/mapped/ShowSiloMinimalMappedMock.ts
- projects/client/src/mocks/data/summary/shows/silo/response/ShowSiloResponseMock.ts
- projects/client/src/mocks/data/users/mapped/HiddenShowProgressMappedMock.ts
- projects/client/src/mocks/data/users/mapped/WatchlistMoviesMappedMock.ts
- projects/client/src/mocks/data/users/mapped/WatchlistShowsMappedMock.ts
- projects/client/src/style/theme/modes.scss
Dark Mode:
https://github.com/user-attachments/assets/4b00ed59-d1b2-437e-b849-5b46079a78c4
Light Mode:
https://github.com/user-attachments/assets/1347ae76-659c-43b0-9e9b-ace9e98acff0
> feat(cover): use gradient on media backdrop

- projects/client/src/lib/components/background/CoverImage.svelte
- banding in the middle of the image is eliminated (before element with blend stops for background fix that)
- color tinting is `much` better with this method and image is much more readable
- fix bug where cover wouldn't be B&W for main covers on mobile
> feat / improve color tinting

- projects/client/src/lib/components/background/CoverImage.svelte
> fix(cover): improve background blending

- projects/client/i18n/messages/bg-bg.json
- projects/client/i18n/messages/da-dk.json
- projects/client/i18n/messages/de-de.json
- projects/client/i18n/messages/en.json
- projects/client/i18n/messages/es-es.json
- projects/client/i18n/messages/es-mx.json
- projects/client/i18n/messages/fr-ca.json
- projects/client/i18n/messages/fr-fr.json
- projects/client/i18n/messages/it-it.json
- projects/client/i18n/messages/ja-jp.json
- projects/client/i18n/messages/nb-no.json
- projects/client/i18n/messages/nl-nl.json
- projects/client/i18n/messages/pl-pl.json
- projects/client/i18n/messages/pt-br.json
- projects/client/i18n/messages/ro-ro.json
- projects/client/i18n/messages/sv-se.json
- projects/client/i18n/messages/uk-ua.json
- projects/client/src/lib/requests/queries/recommendations/RecommendationSourceParams.ts
- projects/client/src/lib/requests/queries/recommendations/_internal/sourceToMethod.ts
- projects/client/src/lib/requests/queries/recommendations/recommendedMoviesQuery.ts
- projects/client/src/lib/requests/queries/recommendations/recommendedShowsQuery.ts
- projects/client/src/lib/sections/lists/recommended/RecommendedList.svelte
- projects/client/src/lib/sections/lists/recommended/RecommendedPaginatedList.svelte
- projects/client/src/lib/sections/lists/recommended/useRecommendedList.ts
- projects/client/src/lib/utils/constants.ts
- projects/client/src/routes/movies/+page.svelte
- projects/client/src/routes/movies/recommended/+page.svelte
- projects/client/src/routes/shows/+page.svelte
- projects/client/src/routes/shows/recommended/+page.svelte
This pull request introduces support for a new recommendation source, "social recommendations," across multiple languages and updates the recommendation query system to accommodate this new source. The most important changes include updates to the internationalization (i18n) files, the addition of a new type for recommendation sources, and modifications to the recommendation query logic.
* Added translations for the new "social_recommendations" key in various i18n files, including `bg-bg.json`, `da-dk.json`, `de-de.json`, `en.json`, `es-es.json`, `es-mx.json`, `fr-ca.json`, `fr-fr.json`, `it-it.json`, `ja-jp.json`, `nb-no.json`, `nl-nl.json`, `pl-pl.json`, `pt-br.json`, `ro-ro.json`, `sv-se.json`, and `uk-ua.json`. [[1]](diffhunk://#diff-31fe4ba5de551c7af03908f5e1468366ab461144f44c04cbd00d …
> feat(recommended): expose experimental social system to directors

- projects/client/src/lib/features/search/SearchInput.svelte
- projects/client/src/routes/_design_system/formatting/dates/+page.svelte
- projects/client/src/style/theme/modes.scss
Updates the border color variable for consistency across the application.
Adds a new page showcasing different date formatting options and their usage, providing clear examples for developers.
> feat / add date formatting examples

- projects/client/src/lib/components/buttons/ActionButton.svelte
- projects/client/src/lib/components/buttons/Button.svelte
- projects/client/src/lib/components/dropdown/TraktDropdownListProps.ts
- projects/client/src/lib/components/lists/section-list/CollapseIcon.svelte
- projects/client/src/lib/components/lists/section-list/ExpandIcon.svelte
- projects/client/src/lib/components/lists/section-list/SectionList.svelte
- projects/client/src/lib/components/lists/section-list/ShadowList.svelte
- projects/client/src/lib/sections/lists/components/ViewAllButton.svelte
- projects/client/src/lib/sections/lists/drilldown/DrillableMediaList.svelte
- projects/client/src/lib/sections/summary/components/comments/Comments.svelte
Updates header actions in lists to utilize the "ghost" button style for a more consistent and visually appealing user interface.
This change ensures better readability, especially when rendered over background images, by adding a backdrop filter.
> feat / update list header actions to use ghost style

- deno.lock
- projects/client/package.json
- projects/client/src/app.d.ts
- projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
- projects/client/src/lib/features/image/components/CrossOriginImage.svelte
- projects/client/src/lib/features/image/components/EditableImage.svelte
- projects/client/src/lib/features/image/components/ImageChangeEvent.ts
- projects/client/src/lib/features/image/components/ImageProps.ts
- projects/client/src/lib/requests/models/InvalidateAction.ts
- projects/client/src/lib/requests/queries/users/uploadAvatarRequest.ts
- projects/client/src/lib/sections/profile-banner/ProfileImage.svelte
- projects/client/src/lib/sections/profile-banner/ProfilePageBanner.svelte
- projects/client/src/lib/utils/actions/dropzone.spec.ts
- projects/client/src/lib/utils/actions/dropzone.ts
- projects/client/src/lib/utils/perf/monitor.spec.ts
- projects/client/src/lib/utils/perf/monitor.ts
- Allows users to upload and change their profile avatar
- Introduces a new `dropzone` action for drag-and-drop image uploads
- Updates `@trakt/api` dependency
- Adds ability to enable performance monitoring on-demand via local storage
> feat / enable user avatar customization

- projects/client/src/lib/sections/summary/components/details/_internal/useMediaDetails.ts
- For shows, always show the status
> feat(summary): always show status for shows

- projects/client/src/lib/sections/lists/stores/useUserSeason.ts
- projects/client/src/routes/shows/[slug]/+page.svelte
Enhances the show page to automatically select the next season if the current season has been fully watched by the user.
- Checks if the current season is fully watched based on the user's history.
- If the current season is fully watched, navigates to the next available season.
> feat / improve show page to preselect next season

- projects/client/src/routes/shows/[slug]/+page.svelte
- Fall back to max season if there is no watch history
Before:
After:
> fix(summary): fall back to max season

- projects/client/src/lib/features/theme/components/ThemeProvider.svelte
- projects/client/src/lib/features/theme/useTheme.ts
- projects/client/src/lib/sections/navbar/Navbar.svelte
- projects/client/src/lib/utils/devices/isPWA.ts
- projects/client/src/routes/+layout.svelte
- projects/client/src/style/theme/modes.scss
Improves the user experience for PWA users and enhances theme integration:
- Introduces `isPWA` utility to detect PWA mode and adjust navbar styles accordingly, removing the border-radius for a native feel.
- Refines theme color application by targeting the navbar specifically.
- Adjusts background gradient on layouts.
> feat / enhance PWA navbar experience and theme integration

- projects/client/src/lib/sections/navbar/Navbar.svelte
Before:
https://github.com/user-attachments/assets/cde6146f-831b-4676-8ffa-b45115500796
After:
https://github.com/user-attachments/assets/dd1ab4b9-136f-4e67-8916-96cd501b6a6a
> feat(navbar): improve ios pwa navbar experience

- projects/client/src/app.html
- projects/client/src/hooks.server.ts
- projects/client/src/lib/features/analytics/AnalyticsProvider.svelte
- projects/client/src/lib/features/analytics/_internal/initialize.ts
- projects/client/src/lib/features/analytics/useAnalytics.ts
- projects/client/src/lib/features/cookie-consent/CookieConsentProvider.svelte
- projects/client/src/lib/features/cookie-consent/useCookieConsent.ts
- projects/client/src/lib/sections/cookie/CookieNotice.svelte
- projects/client/src/routes/+layout.svelte
Do not initialize analytics if we don't have consent yet
> fix(analytics): do not initialize analytics without consent

- projects/client/src/lib/sections/navbar/SideNavbar.svelte
- projects/client/src/lib/sections/navbar/components/BetaBadge.svelte
> feat(tv): show beta badge on TV

- projects/client/src/lib/sections/navbar/components/filter/FilterSidebar.svelte
- projects/client/src/lib/sections/navbar/components/filter/_internal/SaveFiltersButton.svelte
- Closes the filter sidebar on save
https://github.com/user-attachments/assets/cac7c72d-fc46-4d12-a4f9-79e8d9846c85
> fix(filters): close sidebar on save

- projects/client/src/lib/features/auth/handle.ts
- We were omitting our auth endpoint requests 🥲
> fix(auth): do not block auth endpoint requests

- projects/client/src/lib/features/query/useQuery.ts
This PR refactors the `useQuery` hook to improve the query invalidation logic.
**Key Changes:**
*   **Invalidation Trigger:** The invalidation logic is now triggered by a `derived` store that wraps the result of `createQuery`, rather than solely on component mount (`onMount`). This allows the invalidation logic to react to changes in the underlying query state or key.
*   **Invalidation Timing:** Instead of using a fixed `setTimeout` delay, the invalidation now waits asynchronously for the query to reach a stable state (`status: 'success'` and `fetchStatus: 'idle'`) before calling `client.invalidateQueries`. This makes the invalidation more reliable and prevents potential race conditions where invalidation might occur before the initial fetch is complete.
*   **Return Value:** The …
> fix: improve query invalidation logic

- projects/client/src/lib/features/filters/_internal/constants.ts
- projects/client/src/lib/features/filters/_internal/getDefaultFilters.spec.ts
- projects/client/src/lib/features/filters/_internal/getDefaultFilters.ts
- Temporarily disables the streaming filter until the server side issues are fixed.
> fix: temporarily disable streaming filter

- projects/client/src/lib/components/card/CardCover.svelte
- projects/client/src/lib/components/card/CardCoverProps.ts
> chore(cover): remove unused loading parameter

- deno.lock
- projects/client/package.json
- projects/client/src/lib/requests/queries/movies/movieAnticipatedQuery.ts
- projects/client/src/lib/requests/queries/movies/movieHotQuery.ts
- projects/client/src/lib/requests/queries/shows/showAnticipatedQuery.ts
- projects/client/src/lib/requests/queries/shows/showHotQuery.ts
- projects/client/src/lib/utils/date/addYear.spec.ts
- projects/client/src/lib/utils/date/addYear.ts
This pull request updates dependencies, introduces a new utility function for date manipulation, and adjusts API request parameters for consistency and functionality. The most important changes include upgrading the `@trakt/api` dependency, adding the `addYear` utility function, and modifying API requests to use the new utility function for date calculations.
* Updated `@trakt/api` dependency in `package.json` from version `0.2.4` to `0.2.5` to ensure compatibility with the latest API features.
* Added a new `addYear` utility function in `projects/client/src/lib/utils/date/addYear.ts` to calculate a date one year ahead.
* Added comprehensive unit tests for the `addYear` function in `addYear.spec.ts` to validate its behavior, including edge cases like leap years and time preservation.
* …
> feat / upcoming year

- .gitignore
- projects/client/.scripts/traktify-i18n.ts
- projects/client/i18n/generator/core/I18nGenerator.spec.ts
- projects/client/i18n/generator/core/generateFromMeta.spec.ts
- projects/client/i18n/generator/model/MetaMessages.ts
- projects/client/i18n/generator/platform/AndroidGenerator.ts
- projects/client/i18n/generator/platform/IOSGenerator.ts
- projects/client/i18n/generator/platform/WebGenerator.ts
- projects/client/i18n/meta/bg-bg.json
- projects/client/i18n/meta/da-dk.json
- projects/client/i18n/meta/de-de.json
- projects/client/i18n/meta/es-es.json
- projects/client/i18n/meta/es-mx.json
- projects/client/i18n/meta/fr-ca.json
- projects/client/i18n/meta/fr-fr.json
- projects/client/i18n/meta/it-it.json
- projects/client/i18n/meta/ja-jp.json
- projects/client/i18n/meta/nb-no.json
- projects/client/i18n/meta/nl-nl.json
- projects/client/i18n/meta/pl-pl.json
- projects/client/i18n/meta/pt-br.json
- projects/client/i18n/meta/ro-ro.json
- projects/client/i18n/meta/sv-se.json
- projects/client/i18n/meta/uk-ua.json
- projects/client/i18n/schema/meta-messages.schema.json
This PR refines our **internationalization (i18n) pipeline** with several key improvements:
* **Locale-specific translation guidance** has been added to the `MetaMessages` interface and applied to various locales (e.g., Bulgarian for warmth, Danish for hygge). This ensures more culturally nuanced translations.
* Translation prompts now **incorporate these locale instructions**, leading to more accurate generated translations.
* The `updateMetaFileWithTranslations` function now **preserves key order and updates existing messages reliably**.
* **Platform-specific generators** (Android, iOS, Web) have been **simplified** by removing redundant checks, directly accessing default translation values, and reducing code complexity.
These updates collectively provide richer translation context, …
> fix / Improves i18n translation handling

- projects/client/src/lib/features/filters/_internal/constants.ts
- projects/client/src/lib/features/filters/_internal/getDefaultFilters.spec.ts
- projects/client/src/lib/features/filters/_internal/getDefaultFilters.ts
This reverts commit 3a1b161ce0ae9ca6d9d772a23bfee6ada97009ee.
> revert: "fix: temporarily disable streaming filter"

- projects/client/src/lib/components/buttons/share/ShareButton.svelte
- projects/client/src/lib/requests/queries/movies/movieFavoritesQuery.ts
- projects/client/src/lib/requests/queries/shows/showFavoritesQuery.ts
- projects/client/src/lib/sections/lists/FavoritesList.svelte
- projects/client/src/lib/sections/lists/stores/useFavoritesList.ts
- Also applies filters to favorites lists
> fix(favorite): applies filters to favorites lists

- projects/client/src/lib/requests/queries/users/socialActivityQuery.ts
- Invalidates social activity after follow/unfollow.
> fix(requests): invalidates social activity on follow and unfollow

- projects/client/src/lib/features/now-playing/useNowPlaying.ts
Woopsie, forgot to add the onMount 😅
> fix(checkin): only subscribe on mount

- deno.lock
- projects/client/package.json
- Bunch of package updates.
- Follow ups: updates depending on deno/vite updates
- Follow ups 2: one of the dev dep updates broke the preview build; will need to tackle those separately also.
> Chore/ package updates

- projects/client/src/lib/sections/summary/components/comments/_internal/SentimentComment.svelte
- projects/client/src/lib/sections/summary/components/comments/_internal/SentimentHeader.svelte
- Removes the unrealistic sentiment percentages.
> fix(comment): removes unrealistic sentiment percentages

- projects/client/src/lib/features/calendar/Calendar.svelte
- projects/client/src/lib/features/calendar/_internal/scrollToDate.ts
- The loading indicator was the issue..
Before:
https://github.com/user-attachments/assets/61e1f6af-9c86-41e4-9d16-9f090b1bed3a
After:
https://github.com/user-attachments/assets/d27f7500-0ac8-4a73-afdf-72994fe81200
> fix(calendar): force loading indicator desctruction

- .github/workflows/pr_gate.yml
- Use a generated token for enabling auto-merge.
- https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
> ci: use generated tokens to enable auto merge

- projects/client/src/lib/sections/landing/v2/components/JoinForFreeButton.svelte
- Makes the CTA on the landing page a bit more interesting by giving it a bit of a glow animation.
- Since it's not intrusive, I decided to keep it animating instead of just animating it once.
https://github.com/user-attachments/assets/857be830-6f91-464a-9e64-d773cf146123
> feat(landing): make cta more interesting

- projects/client/src/lib/sections/landing/v2/Landing.svelte
- Account for safe area inset on the landing page
> fix(landing): account for safe area inset

- projects/client/src/lib/features/toast/models/LastWatchedItem.ts
- projects/client/src/lib/sections/toast/_internal/useCurrentUserLastWatched.ts
- Only prompt users to rate recently watched movies (at least until we figure out a heuristic to also add show level prompts)
> fix(toast): only prompt for a rating for movies

- projects/client/src/lib/features/cookie-consent/_internal/getConsentCookieValue.ts
- projects/client/src/lib/features/cookie-consent/constants.ts
- projects/client/src/lib/features/cookie-consent/handle.ts
- Use the same consent cookie as OG.
- Legacy cookie is still parsed for users who already gave consent. We can remove that bit later on.
> feat: match consent cookie with OG

- projects/client/src/hooks.client.ts
- Ignore some service worker related errors.
> chore: ignore worker and rejected errors

- projects/client/src/lib/features/auth/queries/currentUserSettingsQuery.ts
- projects/client/src/lib/requests/_internal/mapToUserProfile.ts
- projects/client/src/mocks/data/lists/response/OfficialListsResponseMock.ts
- Adds missing prependHttps for avatars.
> fix(user): prepend avatar url

- projects/client/src/lib/sections/summary/components/_internal/SummaryRateNow.svelte
- projects/client/src/lib/sections/summary/components/rating/RateNow.svelte
- Slide and then fade in the rate buttons.
https://github.com/user-attachments/assets/0b3ae17b-3a67-4375-bcdb-acebda9a0052
> feat(rating): slide and fade in rate buttons

- projects/client/e2e/features/navigate.feature
- projects/client/e2e/support/navigate.steps.ts
- projects/client/e2e/utils/TestUrlBuilder.ts
- projects/client/src/lib/features/auth/components/AuthProvider.svelte
- projects/client/src/lib/sections/navbar/components/TopNavbar.svelte
This pull request introduces improvements to authentication handling and UI behavior based on user authorization status. The main focus is on ensuring navigation security and updating the navbar's visibility and style depending on whether a user is authorized.
**Authentication and navigation enhancements:**
- Added navigation guard in `AuthProvider.svelte` to prevent unauthorized users from accessing protected routes. If an unauthorized user tries to navigate away from the home page, they are redirected back to the home page. [[1]](diffhunk://#diff-d83daf65e76386467a3ce8a3a3d72228ad262ccfd75a581111eb3b2e3c5856a0R2-R3) [[2]](diffhunk://#diff-d83daf65e76386467a3ce8a3a3d72228ad262ccfd75a581111eb3b2e3c5856a0L10-R41)
- Unified the `isAuthorized` logic by combining legacy and OIDC authorization …
> feat(auth) / gate links based on authorization

- projects/client/src/lib/features/auth/stores/useIsMe.ts
- Check the actual value of `isAuthorized`
> fix: check actual authorized state

- projects/client/src/lib/features/errors/ErrorProvider.svelte
- projects/client/src/lib/features/errors/_internal/mapToWellKnownError.ts
- projects/client/src/lib/features/errors/models/CustomFetchError.ts
- projects/client/src/lib/features/errors/models/WellKnownErrors.ts
- projects/client/src/lib/features/query/defineQuery.ts
- projects/client/src/lib/pages/errors/ErrorServicePage.svelte
- On a 503, display server message if present.
> feat(errors): show messages from certain server errors
